---
sidebar: sidebar 
permalink: reregister-scv-vcenter.html 
keywords: re-register SCV with vCenter, recover SCV registration, SCV not connected to vCenter, update vCenter credentials in SCV, unregister SCV extension 
summary: 자격 증명, 네트워크 또는 어플라이언스 변경 후 vCenter에 SCV 등록을 복구하려면 이 작업을 사용하십시오. 
---
= vCenter와의 SCV 연결 및 등록 복구
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere(SCV)는 어플라이언스를 배포할 때 vCenter에 자동으로 등록됩니다. vCenter 암호 변경, SCV IP 주소 또는 호스트 이름 변경, 연결 끊김 또는 부분적인 배포 실패 등으로 등록이 손상된 경우, 이 작업을 사용하여 연결 및 등록을 복구하고 정상 상태인지 확인하십시오.

등록이 성공적으로 완료되지 않으면 다음 작업 중 하나를 사용하여 다시 시도하십시오.

* VMware vSphere 클라이언트 서비스(`scvservice`가 다시 시작됩니다.
* SCV 어플라이언스 IP 주소 또는 호스트 이름이 변경됩니다.
* vCenter 자격 증명이 SCV에 다시 저장됩니다.


.시작하기 전에
* SCV 관리 사용자 인터페이스 IP 주소와 로그온 자격 증명을 알고 있어야 합니다.
* 다중 요소 인증(MFA)이 활성화된 경우 유지 관리 콘솔에서 새 6자리 MFA 토큰을 생성하십시오.
* SCV에서 사용하는 vCenter 계정에 vCenter 루트에서 필요한 권한이 할당되어 있는지 확인하십시오.
+
자세한 내용은 link:scpivs44_minimum_vcenter_privileges_required.html["SCV에 필요한 최소 vCenter 권한"]을 참조하십시오.





== 복구 단계

. VMware vSphere 클라이언트 서비스를 다시 시작하십시오.
+
재시작하면 확장 프로그램 등록이 자동으로 다시 실행됩니다. 자세한 내용은 link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["SCV용 VMware vSphere 클라이언트 서비스를 다시 시작하십시오."]을 참조하십시오.

. 재시작으로 문제가 해결되지 않으면 다음 단계를 완료하십시오.
+
.. SnapCenter Plug-in for VMware vSphere 관리 사용자 인터페이스에  `\https://<appliance-IP-address>:8080` 형식을 사용하여 로그인합니다.
.. *구성* > *vCenter* > *편집*을 선택하십시오.
.. 현재 비밀번호를 입력한 다음 *저장*을 선택합니다.
+
자세한 내용은 link:scpivs44_modify_the_vcenter_logon_credentials.html["SCV에 구성된 vCenter 자격 증명을 업데이트하세요."]을 참조하십시오.



. 플러그인을 등록 해제한 후 다시 등록하십시오.
+
플러그인이 여전히 연결되지 않으면 다음 단계를 완료하십시오.

+
.. vCenter에서 SCV 등록을 취소합니다.
.. vCenter 자격 증명을 다시 저장하거나 VMware vSphere 클라이언트 서비스를 다시 시작하여 SCV를 다시 등록하십시오.
+
등록된 확장 프로그램이 이전 SCV IP 주소를 가리키는 경우 플러그인을 등록 해제한 후 다시 등록하면 등록 정보가 업데이트됩니다.

+
자세한 내용은 link:scpivs44_unregister_plugin_from_vcenter.html["vCenter에서 SnapCenter Plug-in for VMware vSphere 등록 해제"]을 참조하십시오.



. link:#verify-registration-succeeded["등록이 성공했는지 확인하십시오"].




== 등록이 성공했는지 확인하십시오

다음 확인 사항 중 하나를 사용하여 SCV가 등록되고 연결되었는지 확인하십시오.

* *관리 사용자 인터페이스*: *대시보드*에서 SCV가 vCenter에 연결되어 있고 활성화되어 있는지 확인하십시오.
* *vSphere Client*: *SnapCenter Plug-in for VMware vSphere* 메뉴가 표시되고 플러그인 페이지가 로드되는지 확인하십시오.
* *로그(어플라이언스)*:  `/var/log/netapp/vmcontrol/vmcontrol.log`에서  `Registering Aegis as a Vcenter Extension` 및  `Registered com.netapp.aegis extension`와 같은 등록 메시지를 찾으십시오. 자격 증명 변경 사항도  `/var/log/netapp/audit/audit.log`에 기록됩니다.


[NOTE]
====
다음 참조 자료는 고급 문제 해결 용도로만 사용하십시오. 가용성 및 정확한 값은 릴리스 및 환경에 따라 다를 수 있습니다.

* vCenter Extension Manager에서 SCV 관련 확장 `com.netapp.aegis` 및 `com.netapp.scv.client`을 볼 수 있습니다.
* 일부 환경에서는 기존 HTML 클라이언트 확장 프로그램 `com.netapp.scvm.webclient`이 표시될 수도 있습니다.
* 어플라이언스 로그 액세스를 사용할 수 있는 경우 이 항목의 앞부분에서 참조된 등록 관련 항목 및 API 활동을 검토할 수도 있습니다.


====


== 일반적인 등록 오류 및 해결 방법

* *잘못된 로그인 자격 증명*
+
.. 올바른 vCenter 사용자 이름 (`domain\username`과 암호를 다시 입력합니다.
.. 유지 관리 콘솔에서 새로운 6자리 MFA 토큰을 생성하세요.


* *권한 부족(RBAC)*: vCenter 계정에 SCV에 필요한 권한(확장 프로그램 등록 권한 포함)이 vCenter 루트에 할당되어 있는지 확인하십시오.
+
자세한 내용은 link:scpivs44_minimum_vcenter_privileges_required.html["SCV에 필요한 최소 vCenter 권한"]을 참조하십시오.

* *vCenter에 연결할 수 없거나 연결이 거부되었습니다*: vCenter 호스트 및 포트, 네트워크 및 방화벽 연결 상태, 그리고 vCenter가 실행 중인지 확인하십시오.
* *알 수 없는 호스트*: vCenter FQDN 또는 IP 주소를 확인하고 어플라이언스에서 DNS 확인이 정상적으로 작동하는지 확인하십시오.
* *지원되지 않는 vCenter 버전*: SCV는 vCenter Server 7.0U1 이상 버전을 지원합니다.
+
자세한 내용은 link:scpivs44_deployment_planning_and_requirements.html["SCV 구축 계획 및 요구 사항"]을 참조하십시오.

* *서비스가 실행 중이 아님*: VMware vSphere 클라이언트 서비스가 중지된 경우 등록을 실행할 수 없습니다.
+
VMware vSphere 클라이언트 서비스를 다시 시작하십시오.





== 관련 주제

* link:scpivs44_modify_the_vcenter_logon_credentials.html["SCV에 구성된 vCenter 자격 증명을 업데이트하세요."]
* link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["SCV용 VMware vSphere 클라이언트 서비스를 다시 시작하십시오."]
* link:scpivs44_unregister_plugin_from_vcenter.html["vCenter에서 SnapCenter Plug-in for VMware vSphere 등록 해제"]
* link:scpivs44_minimum_vcenter_privileges_required.html["SCV에 필요한 최소 vCenter 권한"]

