---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html 
keywords:  
summary: SnapCenter 기능을 사용하여 가상 머신에서 VM, 데이터 저장소 및 애플리케이션 정합성이 보장되는 데이터베이스를 보호하려면 VMware vSphere용 SnapCenter 플러그인을 구축해야 합니다. 
---
= VMware vSphere용 SnapCenter 플러그인 구축
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter 기능을 사용하여 가상 머신에서 VM, 데이터 저장소 및 애플리케이션 정합성이 보장되는 데이터베이스를 보호하려면 VMware vSphere용 SnapCenter 플러그인을 구축해야 합니다.

.시작하기 전에
이 섹션에는 배포를 시작하기 전에 수행해야 하는 모든 필수 작업이 나열되어 있습니다.


NOTE:  OVA 구축은 VMware vCenter 7u1 이상에서 지원됩니다.

* 구축 요구 사항을 읽어야 합니다.
* 지원되는 버전의 vCenter Server를 실행 중이어야 합니다.
* vCenter Server 환경을 구성하고 설정해야 합니다.
* SnapCenter Plug-in for VMware vSphere VM용 ESXi 호스트를 설정해야 합니다.
* SnapCenter Plug-in for VMware vSphere.tar 파일을 다운로드해야 합니다.
* vCenter Server 인스턴스에 대한 로그인 인증 세부 정보가 있어야 합니다.
* 유효한 공개 및 개인 키 파일이 있는 인증서가 있어야 합니다. 자세한 내용은 섹션의 문서를 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_Certificate_Resolution_Guide["스토리지 인증서 관리"] 참조하십시오.
* SnapCenter Plug-in for VMware vSphere를 배포하는 동안 브라우저 캐시 문제가 발생하지 않도록 vSphere Client의 모든 브라우저 세션을 로그아웃했다가 닫고 브라우저 캐시를 삭제해야 합니다.
* vCenter에서 TLS(Transport Layer Security)를 활성화해야 합니다. VMware 설명서를 참조하십시오.
* SnapCenter Plug-in for VMware vSphere가 구축된 vCenter 이외의 vCenter에서 백업을 수행하려면 ESXi 서버, VMware vSphere용 SnapCenter 플러그인 및 각 vCenter를 동시에 동기화해야 합니다.
* VVOL 데이터 저장소에서 VM을 보호하려면 먼저 VMware vSphere용 ONTAP 툴을 구축해야 합니다. VMware vSphere 버전 9.10 이상용 ONTAP 툴이 지원됩니다. ONTAP 툴은 ONTAP 및 VMware 웹 클라이언트에서 스토리지를 프로비저닝하고 구성합니다.


vCenter와 동일한 시간대에 VMware vSphere용 SnapCenter 플러그인을 구축합니다. 백업 스케줄은 VMware vSphere용 SnapCenter 플러그인이 구축되는 표준 시간대에서 실행됩니다. vCenter는 vCenter가 있는 시간대의 데이터를 보고합니다. 따라서 VMware vSphere 및 vCenter용 SnapCenter 플러그인이 서로 다른 시간대에 있는 경우 VMware vSphere용 SnapCenter 플러그인 대시보드의 데이터가 보고서의 데이터와 같지 않을 수 있습니다.

.단계
. VMware vCenter 7.0.3 이상 버전의 경우 의 단계를 따릅니다 link:scpivs44_download_the_ova_open_virtual_appliance.html["OVA(Open Virtual Appliance) 다운로드"^] vCenter로 인증서를 가져옵니다.
. 브라우저에서 VMware vSphere vCenter로 이동합니다.
+

NOTE: IPv6 HTML 웹 클라이언트의 경우 Chrome 또는 Firefox를 사용해야 합니다.

. VMware vCenter Single Sign-On * 페이지에 로그인합니다.
. 탐색기 창에서 데이터 센터, 클러스터 또는 호스트와 같이 가상 시스템의 유효한 상위 객체인 인벤토리 객체를 마우스 오른쪽 버튼으로 클릭하고 * Deploy OVF Template * 을 선택하여 VMware 배포 마법사를 시작합니다.
. 로컬 시스템에 .ova 파일이 포함된 .tar 파일의 압축을 풉니다. OVF 템플릿 선택 * 페이지에서 의 위치를 지정합니다 `.ova` tar extracted 폴더 안의 파일입니다.
. 다음 * 을 클릭합니다.
. 이름 및 폴더 선택 * 페이지에서 VM 또는 vApp의 고유한 이름을 입력하고 구축 위치를 선택한 후 * 다음 * 을 클릭합니다.
+
이 단계는 를 가져올 위치를 지정합니다 `.tar` 파일을 vCenter에 저장합니다. VM의 기본 이름은 선택한 의 이름과 같습니다 `.ova` 파일. 기본 이름을 변경하는 경우 각 vCenter Server VM 폴더 내에서 고유한 이름을 선택합니다.

+
VM의 기본 배포 위치는 마법사를 시작한 인벤토리 객체입니다.

. 리소스 선택 * 페이지에서 배포된 VM 템플릿을 실행할 리소스를 선택하고 * 다음 * 을 클릭합니다.
. Review details * 페이지에서 를 확인합니다 `.tar` 템플릿 세부 정보를 입력하고 * 다음 * 을 클릭합니다.
. License Agreement * 페이지에서 * I accept all license Agreement * 확인란을 선택합니다.
. Select storage * 페이지에서 배포된 OVF 템플릿에 대한 파일의 저장 위치 및 방법을 정의합니다.
+
.. VMDK의 디스크 형식을 선택합니다.
.. VM 스토리지 정책을 선택합니다.
+
이 옵션은 대상 리소스에 스토리지 정책이 설정된 경우에만 사용할 수 있습니다.

.. 구축된 OVA 템플릿을 저장할 데이터 저장소를 선택합니다.
+
구성 파일 및 가상 디스크 파일은 데이터 저장소에 저장됩니다.

+
가상 머신 또는 vApp과 연결된 모든 가상 디스크 파일을 수용할 수 있을 만큼 큰 데이터 저장소를 선택합니다.



. 네트워크 선택 * 페이지에서 다음을 수행합니다.
+
.. 소스 네트워크를 선택하고 대상 네트워크에 매핑합니다.
+
소스 네트워크 열에는 OVA 템플릿에 정의된 모든 네트워크가 나열됩니다.

.. IP 할당 설정 * 섹션에서 필요한 IP 주소 프로토콜을 선택한 후 * 다음 * 을 클릭합니다.
+
VMware vSphere용 SnapCenter 플러그인은 하나의 네트워크 인터페이스를 지원합니다. 여러 네트워크 어댑터가 필요한 경우 수동으로 설정해야 합니다. 을 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_additional_network_adapters_in_NDB_and_SCV_4.3["KB 문서: 추가 네트워크 어댑터를 만드는 방법"^]참조하십시오.



. 템플릿 사용자 정의 * 페이지에서 다음을 수행합니다.
+
.. 기존 vCenter * 에 등록 섹션에서 vCenter 이름과 가상 어플라이언스의 vCenter 자격 증명을 입력합니다.
+
vCenter 사용자 이름 * 필드에 사용자 이름을 domain\username 형식으로 입력합니다.

.. SCV 자격 증명 만들기 * 섹션에서 로컬 자격 증명을 입력합니다.
+
사용자 이름 * 필드에 로컬 사용자 이름을 입력합니다. 도메인 세부 정보는 포함하지 마십시오.

+

IMPORTANT: 지정한 사용자 이름과 암호를 기록해 둡니다. 나중에 VMware vSphere용 SnapCenter 플러그인 구성을 수정하려면 이러한 자격 증명을 사용해야 합니다.

.. 유지보수 사용자의 자격 증명을 입력합니다.
.. Setup Network Properties * 섹션에서 호스트 이름을 입력합니다.
+
... Setup IPv4 Network Properties * 섹션에서 IPv4 주소, IPv4 넷마스크, IPv4 게이트웨이, IPv4 기본 DNS, IPv4 보조 DNS, 및 IPv4 검색 도메인.
... IPv6 네트워크 속성 설정 * 섹션에서 IPv6 주소, IPv6 넷마스크, IPv6 게이트웨이, IPv6 기본 DNS, IPv6 보조 DNS, 및 IPv6 검색 도메인.
+
IPv4 또는 IPv6 필드를 선택하거나 둘 다 선택합니다(해당하는 경우). IPv4와 IPv6를 모두 사용하는 경우 둘 중 하나에 대해 Primary DNS를 지정해야 합니다.

+

IMPORTANT: 네트워크 구성으로 DHCP를 계속 진행하려면 이 단계를 건너뛰고 * 네트워크 속성 설정 * 섹션에서 항목을 비워 둘 수 있습니다.



.. Setup Date and Time * 에서 vCenter가 있는 시간대를 선택합니다.


. 완료 준비 완료 * 페이지에서 페이지를 검토하고 * 마침 * 을 클릭합니다.
+
모든 호스트는 IP 주소로 구성되어야 합니다(FQDN 호스트 이름은 지원되지 않음). 배포 작업을 수행해도 사용자 입력의 유효성을 검사하지 않습니다.

+
OVF 가져오기 및 배포 작업이 완료될 때까지 기다리는 동안 Recent Tasks 창에서 구축 진행률을 볼 수 있습니다.

+
SnapCenter Plug-in for VMware vSphere가 성공적으로 구축되면 Linux VM으로 구축되고 vCenter에 등록되며 VMware vSphere Client가 설치됩니다.

. SnapCenter Plug-in for VMware vSphere가 구축된 VM으로 이동한 다음 * Summary * 탭을 클릭하고 * Power On * 상자를 클릭하여 가상 어플라이언스를 시작합니다.
. VMware vSphere용 SnapCenter 플러그인의 전원이 켜지는 동안 배포된 VMware vSphere용 SnapCenter 플러그인을 마우스 오른쪽 단추로 클릭하고 * 게스트 OS * 를 선택한 다음 * VMware 도구 설치 * 를 클릭합니다.
+
VMware 툴은 VMware vSphere용 SnapCenter 플러그인이 구축된 VM에 설치됩니다. VMware 툴 설치에 대한 자세한 내용은 VMware 설명서를 참조하십시오.

+
배포를 완료하는 데 몇 분 정도 걸릴 수 있습니다. VMware vSphere용 SnapCenter 플러그인의 전원이 켜지고 VMware 툴이 설치되며 VMware vSphere용 SnapCenter 플러그인에 로그인하라는 메시지가 화면에 표시되면 구축이 성공한 것입니다. 처음 재부팅할 때 네트워크 구성을 DHCP에서 정위치로 전환할 수 있습니다. 그러나 정적에서 DHCP로의 전환은 지원되지 않습니다.

+
화면에 VMware vSphere용 SnapCenter 플러그인이 구축된 IP 주소가 표시됩니다. IP 주소를 기록해 둡니다. VMware vSphere용 SnapCenter 플러그인 구성을 변경하려면 VMware vSphere 관리 GUI용 SnapCenter 플러그인 에 로그인해야 합니다.

. 구축 화면에 표시된 IP 주소와 구축 마법사에서 제공한 자격 증명을 사용하여 VMware vSphere 관리 GUI용 SnapCenter 플러그인 에 로그인합니다. 그런 다음 대시보드에서 VMware vSphere용 SnapCenter 플러그인이 vCenter에 연결되고 활성화되어 있는지 확인합니다.
+
형식을 사용합니다 `\https://<appliance-IP-address>:8080` 관리 GUI에 액세스합니다.

+
배포 시 설정된 admin 사용자 이름과 암호 및 유지보수 콘솔을 사용하여 생성된 MFA 토큰으로 로그인합니다.

+
VMware vSphere용 SnapCenter 플러그인이 활성화되어 있지 않으면 을 참조하십시오 link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["VMware vSphere Client 서비스를 다시 시작합니다"].

+
호스트 이름이 'UnifiedVSC/SCV'인 경우 어플라이언스를 다시 시작합니다. 어플라이언스를 다시 시작해도 호스트 이름이 지정된 호스트 이름으로 변경되지 않으면 어플라이언스를 다시 설치해야 합니다.



.작업을 마친 후
필수 를 완료해야 합니다 link:scpivs44_post_deployment_required_operations_and_issues.html["구축 후 작업"].
