---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: 백업 리소스 그룹을 생성, 수정 및 삭제하고 리소스 그룹에 대한 백업 작업을 수행할 수 있습니다. 
---
= 자원 그룹을 관리합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
백업 리소스 그룹을 생성, 수정 및 삭제하고 리소스 그룹에 대한 백업 작업을 수행할 수 있습니다.


NOTE: 리소스 그룹을 VSC(가상 스토리지 콘솔)에서 백업 작업이라고 합니다.



== 자원 그룹에 대한 작업을 일시 중지하고 다시 시작합니다

리소스 그룹에서 예약된 작업을 일시 중지합니다.  필요할 때 다시 활성화하세요.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 * 리소스 그룹 * 을 선택하고 리소스 그룹을 선택한 다음 * 일시 중단 * 을 선택합니다(또는 * 재시작 * 선택).
. 확인 상자에서 * 확인 * 을 선택하여 확인합니다.


.작업을 마친 후
자원 그룹 페이지에서 일시 중단된 자원의 작업 상태는 "Under_Maintenance"입니다. 작업 상태 열을 보려면 테이블 오른쪽으로 스크롤해야 할 수 있습니다.

백업 작업이 재개되면 작업 상태가 운영 상태로 변경됩니다.



== 리소스 그룹을 수정합니다

vCenter의 리소스 그룹에서 리소스를 제거 또는 추가하거나 정책을 분리 또는 첨부하거나 스케줄을 수정하거나 다른 리소스 그룹 옵션을 수정할 수 있습니다.

.이 작업에 대해
리소스 그룹의 이름을 수정하려면 VM, 데이터 저장소, 정책, 백업 또는 리소스 그룹 이름에 다음 특수 문자를 사용하지 마십시오.

%& * $#@! /: *? " < > - | ; ' , 그리고 공백. 밑줄 문자(_)를 사용할 수 있습니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 * 리소스 그룹 * 을 선택한 다음 리소스 그룹을 선택하고 * 편집 * 을 선택합니다.
. 자원 그룹 편집* 마법사의 왼쪽 목록에서 수정할 범주를 선택하고 변경 내용을 입력합니다.
+
여러 범주에서 변경할 수 있습니다. 이 옵션에서 보조 보호 리소스를 편집할 수도 있습니다.

. 요약 페이지가 표시될 때까지 * 다음 * 을 선택한 다음 * 마침 * 을 선택합니다.




== 리소스 그룹을 삭제합니다

리소스를 보호할 필요가 없는 경우 vCenter에서 리소스 그룹을 삭제합니다.  SnapCenter Plug-in for VMware vSphere 제거하기 전에 모든 리소스 그룹을 삭제하세요.

.이 작업에 대해
모든 리소스 그룹 삭제 작업은 강제 삭제로 수행됩니다.  리소스 그룹을 삭제하면 시스템은 vCenter 리소스 그룹에서 모든 정책을 분리하고, SnapCenter Plug-in for VMware vSphere 에서 리소스 그룹을 제거하고, 리소스 그룹의 모든 백업과 스냅샷을 삭제합니다.


NOTE: SnapVault 관계에서는 마지막 스냅샷을 삭제할 수 없으므로 리소스 그룹을 삭제할 수 없습니다.  SnapVault 관계에서 리소스 그룹을 삭제하기 전에 System Manager나 ONTAP CLI를 사용하여 관계를 제거한 다음 마지막 스냅샷을 삭제합니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 * 리소스 그룹 * 을 선택한 다음 리소스 그룹을 선택하고 * 삭제 * 를 선택합니다.
. *리소스 그룹 삭제* 확인 대화 상자에서 *확인*을 선택하여 확인합니다.  리소스 그룹을 삭제해도 보조 보호는 제거되지 않습니다.  필요한 경우 시스템 관리자를 사용하여 보조 보호 기능을 삭제하세요.  리소스 그룹에 대해 생성된 일관성 그룹은 자동으로 제거되지 않습니다. System Manager나 지원되는 다른 인터페이스를 사용하여 ONTAP 에서 수동으로 삭제해야 합니다.

