---
sidebar: sidebar 
permalink: scpivs44_create_backup_policies_for_vms_and_datastores.html 
keywords:  
summary: VMware vSphere용 SnapCenter 플러그인을 사용하여 VM 및 데이터 저장소를 백업하려면 먼저 백업 정책을 생성해야 합니다. 
---
= VM 및 데이터 저장소에 대한 백업 정책을 생성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware vSphere용 SnapCenter 플러그인을 사용하여 VM 및 데이터 저장소를 백업하려면 먼저 백업 정책을 생성해야 합니다.

.시작하기 전에
* 필수 구성 요소를 읽어야 합니다.
* 2차 스토리지 관계가 구성되어 있어야 합니다.
+
** 스냅샷 복사본을 미러 또는 볼트 보조 스토리지로 복제하는 경우 관계를 구성해야 하며 SnapCenter 관리자는 소스 볼륨과 타겟 볼륨 모두에 대해 스토리지 VM을 사용자에게 할당해야 합니다.
** NFS 또는 VMFS 데이터 저장소에서 Version - FlexibleMirror 관계를 위해 스냅샷 복제본을 보조 스토리지로 성공적으로 전송하려면 SnapMirror 정책 유형이 Asynchronous Mirror이고 "All_source_snapshots" 옵션이 선택되어 있는지 확인합니다.
** 보조 스토리지(미러 소산)의 스냅샷 복사본 수가 최대 제한에 도달하면 백업 등록 및 백업 작업에 보존을 적용하는 작업이 실패하고 "이 스냅샷 복사본은 현재 하나 이상의 SnapMirror 관계에 의해 참조 스냅샷 복사본으로 사용됩니다. Snapshot 복사본을 삭제하면 향후 SnapMirror 작업이 실패할 수 있습니다.
+
이 문제를 해결하려면 스냅샷 복사본의 최대 제한에 도달하지 않도록 보조 스토리지에 대한 SnapMirror 보존 정책을 구성하십시오.

+
관리자가 사용자에게 리소스를 할당하는 방법에 대한 자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/snapcenter/concept/concept_types_of_role_based_access_control_in_snapcenter.html["역할 기반 액세스 제어 사용에 대한 SnapCenter 정보"^].



* VM 정합성 보장 백업을 원할 경우 VMware 도구가 설치되어 실행 중이어야 합니다. VM을 중지하려면 VMware 툴이 필요합니다. VM 일치 백업은 VVOL VM에 대해 지원되지 않습니다.


.이 작업에 대해
이 마법사 페이지의 대부분의 필드는 설명이 필요 없습니다. 다음 정보는 안내가 필요할 수 있는 일부 필드에 대해 설명합니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 * Policies * 를 클릭합니다.
. Policies * 페이지에서 * Create * 를 선택하여 마법사를 시작합니다.
. 새 백업 정책 * 페이지에서 정책을 사용할 vCenter Server를 선택한 다음 정책 이름과 설명을 입력합니다.
+
** 링크 모드
+
연결 모드에서는 각 vCenter에 별도의 가상 어플라이언스가 있습니다. 따라서 vCenter 전체에서 중복 이름을 사용할 수 있습니다. 그러나 리소스 그룹과 동일한 vCenter에서 정책을 생성해야 합니다.

** 지원되지 않는 문자입니다
+
VM, 데이터 저장소, 클러스터, 정책, 백업, 또는 리소스 그룹 이름: %& * $#@! /: *? "<>-|;',.

+
밑줄 문자(_)를 사용할 수 있습니다.



. 보존 설정을 지정합니다.
+

IMPORTANT: SnapVault 복제를 사용하도록 설정하려는 경우 보존 수를 백업 2개 이상으로 설정해야 합니다. 보존 개수를 1개의 백업으로 설정하면 보존 작업이 실패할 수 있습니다. 그 이유는 첫 번째 스냅샷 복사본이 SnapVault 관계에 대한 참조 스냅샷 복사본으로, 새로운 스냅샷 복사본이 타겟으로 복제되기 때문입니다.

+

NOTE: 최대 보존 값은 ONTAP 9.4 이상의 리소스에 대한 1018 백업과 ONTAP 9.3 이전 버전의 리소스에 대한 254 백업입니다. 보존이 기본 ONTAP 버전에서 지원하는 값보다 높은 값으로 설정된 경우 백업이 실패합니다. 데이터 저장소 스패닝 시에도 마찬가지입니다. 스패닝 데이터 저장소에 ONTAP 9.3 이전 및 ONTAP 9.4 이상 버전의 리소스가 포함되어 있는 경우 보존 값을 254 미만으로 설정해야 합니다.

. 주파수 설정을 지정합니다.
+
정책은 백업 빈도만 지정합니다. 백업에 대한 특정 보호 스케줄은 리소스 그룹에 정의됩니다. 따라서 둘 이상의 리소스 그룹이 동일한 정책 및 백업 빈도를 공유할 수 있지만 백업 스케줄은 다릅니다.

. 다음 표와 같이 * Replication * 필드에서 보조 스토리지에 대한 복제 유형을 지정합니다.
+
|===
| 이 필드의 경우… | 이렇게 하십시오. 


| 백업 후 SnapMirror를 업데이트합니다  a| 
운영 백업 볼륨과 SnapMirror 관계가 있는 다른 볼륨에 백업 세트의 미러 복사본을 생성하려면 이 옵션을 선택합니다. 볼륨이 미러 볼트 관계로 구성된 경우 미러 볼트 대상에 백업을 복사하려면 * 백업 후 SnapVault 업데이트 * 옵션만 선택해야 합니다.


NOTE: 이 옵션은 VMware vSphere 4.5 이상 버전용 SnapCenter 플러그인의 FlexGroup 볼륨에 있는 데이터 저장소에 대해 지원됩니다.



| 백업 후 SnapVault를 업데이트합니다  a| 
기본 백업 볼륨과 SnapVault 관계가 있는 다른 볼륨에서 D2D 백업 복제를 수행하려면 이 옵션을 선택합니다.


IMPORTANT: 볼륨이 미러 볼트 관계로 구성된 경우 백업을 미러 볼트 대상에 복사하려면 이 옵션만 선택해야 합니다.


NOTE: 이 옵션은 VMware vSphere 4.5 이상 버전용 SnapCenter 플러그인의 FlexGroup 볼륨에 있는 데이터 저장소에 대해 지원됩니다.



| 스냅샷 레이블  a| 
이 정책으로 생성된 SnapVault 및 SnapMirror Snapshot 복사본에 추가할 선택적 사용자 지정 레이블을 입력합니다. 스냅샷 레이블을 사용하면 이 정책으로 생성된 스냅샷을 보조 스토리지 시스템의 다른 스냅샷과 구분할 수 있습니다.


NOTE: 스냅샷 복사본 레이블에는 최대 31자를 사용할 수 있습니다.

|===
. 선택 사항: * 고급 * 필드에서 필요한 필드를 선택합니다. 고급 필드 세부 정보가 다음 표에 나열되어 있습니다.
+
|===
| 이 필드의 경우… | 이렇게 하십시오. 


| VM 일관성  a| 
백업 작업이 실행될 때마다 VM을 중지하고 VMware 스냅샷을 생성하려면 이 확인란을 선택합니다.

이 옵션은 VVOL에 대해 지원되지 않습니다. VVOL VM의 경우 충돌 시에도 정합성 보장 백업만 수행됩니다.


IMPORTANT: VM 정합성 보장 백업을 수행하려면 VM에서 실행 중인 VMware 툴이 있어야 합니다. VMware Tools가 실행되고 있지 않으면 장애 발생 시 정합성이 보장되는 백업이 대신 수행됩니다.


NOTE: VM 일관성 상자를 선택하면 백업 작업에 더 많은 시간이 걸리고 더 많은 스토리지 공간이 필요할 수 있습니다. 이 시나리오에서는 VM이 먼저 중지된 다음 VMware가 VM 정합성 보장 스냅샷을 수행한 다음 SnapCenter가 백업 작업을 수행한 다음 VM 작업이 다시 시작됩니다. VM 게스트 메모리는 VM 정합성 보장 스냅샷에 포함되지 않습니다.



| 독립 디스크가 있는 데이터 저장소를 포함합니다 | 임시 데이터를 포함하는 독립 디스크가 있는 모든 데이터 저장소를 백업에 포함하려면 이 확인란을 선택합니다. 


| 스크립트  a| 
백업 작업 전후에 SnapCenter VMware 플러그인을 실행할 처방이나 PS의 정규화된 경로를 입력합니다. 예를 들어 스크립트를 실행하여 SNMP 트랩을 업데이트하고, 경고를 자동화하고, 로그를 보낼 수 있습니다. 스크립트 경로는 스크립트가 실행될 때 검증됩니다.


NOTE: 사전 스크립트 및 사후 스크립트는 가상 어플라이언스 VM에 있어야 합니다. 여러 스크립트를 입력하려면 각 스크립트 경로 뒤에 * Enter * 를 눌러 각 스크립트를 별도의 줄에 나열합니다. ";" 문자는 허용되지 않습니다.

|===
. 추가 * 를 클릭합니다
+
정책 페이지에서 정책을 선택하여 정책이 생성되었는지 확인하고 정책 구성을 검토할 수 있습니다.


