---
sidebar: sidebar 
permalink: scpivs44_concepts_overview.html 
keywords:  
summary: 'VMware vSphere용 SnapCenter 플러그인은 VM 및 데이터 저장소에 대한 데이터 보호 서비스를 제공하고 SnapCenter 애플리케이션 기반 플러그인에 대한 데이터 보호 서비스를 지원하는 독립 실행형 가상 어플라이언스(오픈 가상 어플라이언스 형식)입니다. 이 문서에서는 VMware vSphere용 SnapCenter 플러그인을 구축 및 사용하는 방법과 빠른 시작 정보를 제공합니다.' 
---
= 제품 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


VMware vSphere용 SnapCenter 플러그인은 VM 및 데이터 저장소에 대한 데이터 보호 서비스를 제공하고 SnapCenter 애플리케이션 기반 플러그인에 대한 데이터 보호 서비스를 지원하는 독립 실행형 가상 어플라이언스(오픈 가상 어플라이언스 형식)입니다. 이 문서에서는 VMware vSphere용 SnapCenter 플러그인을 구축 및 사용하는 방법과 빠른 시작 정보를 제공합니다.

VMware vSphere용 SnapCenter 플러그인은 Linux 기반 가상 어플라이언스로 구축됩니다.

SnapCenter VMware 플러그인에는 사용자 환경에 다음과 같은 기능이 추가됩니다.

* VM 일관성 및 충돌 시에도 정합성 보장 데이터 보호 작업 지원
+
vCenter에서 VMware vSphere 웹 클라이언트 GUI를 사용하여 VMware 가상 머신(기존 VM 및 VVOL VM), VMDK 및 데이터 저장소의 모든 백업 및 복원 작업을 수행할 수 있습니다. VVOL VM(VVOL 데이터 저장소의 VM)의 경우 충돌 시에도 정합성 보장 백업만 지원됩니다. VM 및 VMDK를 복구하고 게스트 OS에 상주하는 파일 및 폴더를 복원할 수도 있습니다.

+
VM, VMDK 및 데이터 저장소를 백업할 때 플러그인은 RDM을 지원하지 않습니다. VM의 백업 작업은 RDM을 무시합니다. RDM을 백업해야 하는 경우에는 SnapCenter 애플리케이션 기반 플러그인을 사용해야 합니다.

+
SnapCenter VMware 플러그인에는 SnapCenter VMware 플러그인 메타데이터가 포함된 MySQL 데이터베이스가 포함됩니다. VM 일관성 및 장애 발생 시 정합성이 보장되는 데이터 보호를 위해 SnapCenter 서버를 설치할 필요가 없습니다.

* 애플리케이션 정합성 보장(VMDK/RDM을 통한 애플리케이션) 데이터 보호 작업 지원
+
SnapCenter GUI와 적절한 SnapCenter 애플리케이션 플러그인을 사용하여 VM의 운영 및 보조 스토리지에 있는 데이터베이스 및 파일 시스템의 모든 백업 및 복원 작업을 수행할 수 있습니다.

+
SnapCenter는 기본적으로 VMDK, RDM(Raw Device Mapping) 및 NFS 데이터 저장소의 모든 데이터 보호 작업에 SnapCenter VMware 플러그인을 활용합니다. 가상 어플라이언스가 구축된 후에는 플러그인이 vCenter와의 모든 상호 작용을 처리합니다. SnapCenter VMware 플러그인은 모든 SnapCenter 애플리케이션 기반 플러그인을 지원합니다.

+
SnapCenter은 데이터베이스와 VM의 단일 스냅샷 복사본을 함께 지원하지 않습니다. VM 및 데이터베이스의 백업은 별도로 예약 및 실행해야 하며, 데이터베이스와 VM이 동일한 볼륨에서 호스팅되는 경우에도 별도의 Snapshot 복사본이 생성됩니다. SnapCenter GUI를 사용하여 데이터베이스 애플리케이션 백업을 예약해야 하며, VMware vSphere 웹 클라이언트 GUI를 사용하여 VM 및 데이터 저장소 백업을 예약해야 합니다.

* VM의 일관된 스냅샷 복사본을 사용하려면 VMware 툴이 필요합니다
+
VMware Tools가 설치되어 실행되고 있지 않으면 파일 시스템이 중지되지 않고 장애 발생 시 정합성이 보장되는 스냅샷이 생성됩니다.

* VMware Storage vMotion은 SAN(VMFS) 환경의 복구 작업에 필요합니다
+
VMware 파일 시스템(VMFS)의 복구 워크플로에서는 VMware Storage vMotion 기능을 사용합니다. Storage vMotion은 vSphere Standard 라이센스의 일부이지만 vSphere Essentials 또는 Essentials Plus 라이센스에는 사용할 수 없습니다.

+
NFS 환경에서 수행되는 대부분의 복구 작업은 네이티브 ONTAP 기능(예: 단일 파일 SnapRestore)을 사용하며 VMware Storage vMotion이 필요하지 않습니다.

* VMware VVOL VM을 보호하려면 VMware vSphere용 ONTAP 툴이 필요합니다.
+
ONTAP 툴을 사용하여 ONTAP 및 VMware 웹 클라이언트에서 VVOL의 스토리지를 프로비저닝하고 구성할 수 있습니다.

+
자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["VMware vSphere용 ONTAP 툴"^]

* SnapCenter VMware 플러그인은 Linux VM에서 가상 어플라이언스로 구축됩니다
+
가상 어플라이언스를 Linux VM으로 설치해야 하지만 SnapCenter VMware 플러그인은 Windows 기반 및 Linux 기반 vCenter를 모두 지원합니다. SnapCenter는 기본적으로 사용자 개입 없이 이 플러그인을 사용하여 vCenter와 통신하여 Windows 및 Linux 가상화 애플리케이션에서 데이터 보호 작업을 수행하는 SnapCenter 애플리케이션 기반 플러그인을 지원합니다.



이러한 주요 기능 외에도 VMware vSphere용 SnapCenter 플러그인은 NFS 3.0 및 4.1을 통한 iSCSI, 파이버 채널, FCoE, VMDK 및 VMFS 5.0 및 6.0을 통한 VMDK를 지원합니다.

지원되는 버전에 대한 최신 정보는 를 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=103284;&solution=1517&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^] (IMT).

NFS 프로토콜 및 ESXi에 대한 자세한 내용은 VMware에서 제공하는 vSphere 스토리지 설명서를 참조하십시오.

SnapCenter 데이터 보호에 대한 자세한 내용은 에서 SnapCenter 플러그인의 데이터 보호 정보를 참조하십시오 http://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter 문서"^].

지원되는 업그레이드 및 마이그레이션 경로에 대한 자세한 내용은 를 참조하십시오 link:scpivs44_release_notes.html["VMware vSphere용 SnapCenter 플러그인 릴리즈 노트"^].
