---
sidebar: sidebar 
permalink: scpivs44_remove_plugin.html 
keywords:  
summary: SnapCenter 데이터 보호 기능을 더 이상 사용할 필요가 없는 경우 vCenter에서 SnapCenter 플러그인을 등록 해제하려면 SnapCenter VMware 플러그인을 해제한 다음 vCenter에서 VMware 플러그인을 제거한 다음 나머지 파일을 수동으로 삭제해야 합니다. 
---
= VMware vSphere용 SnapCenter 플러그인을 제거합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter 데이터 보호 기능을 더 이상 사용할 필요가 없는 경우 vCenter에서 SnapCenter 플러그인을 등록 해제하려면 SnapCenter VMware 플러그인을 해제한 다음 vCenter에서 VMware 플러그인을 제거한 다음 나머지 파일을 수동으로 삭제해야 합니다.

.시작하기 전에
* 관리자 권한이 있어야 합니다.
* 실행 중인 SnapCenter 작업이 없는지 확인합니다.


.단계
. https://<OVA-IP-address>:8080` 형식으로 SnapCenter VMware 플러그인 관리 GUI에 로그인합니다.
+
플러그인을 배포하면 SnapCenter VMware 플러그인의 IP가 표시됩니다.

. 왼쪽 탐색 창에서 * 구성 * 을 클릭한 다음 * 플러그인 세부 정보 * 섹션에서 서비스 옵션을 선택 취소하여 플러그인을 비활성화합니다.
. VMware vSphere에 로그인합니다.
. 왼쪽 탐색 화면에서 SnapCenter VMware 플러그인(가상 어플라이언스를 배포할 때 사용한 ".ova" 파일의 이름)의 인스턴스를 마우스 오른쪽 버튼으로 클릭하고 * Delete from Disk * 를 선택합니다.
. "/etc/vmware/vsphere-ui/vc-packages/vsphere-client-environment/com.netapp.scvm.webclient-4.5.0.5942045/plugins` 로 이동하여 vCenter Server의 픽업 폴더에서 다음 파일을 수동으로 삭제합니다.
+
VSC-httpclient3-security.jar CV-api-model.jar's CVM_WebUI_service.jar's CVM_WebUI_UI.war'gson-2.5.jar

. SnapCenter VMware 플러그인을 사용하여 애플리케이션 정합성 보장 백업을 위한 다른 SnapCenter 플러그인을 지원했다면 SnapCenter에 로그인하여 vSphere 호스트를 제거하십시오.


가상 어플라이언스는 아직 구축되었지만 SnapCenter VMware 플러그인은 제거되었습니다.

SnapCenter VMware 플러그인용 호스트 VM을 제거한 후에는 로컬 vCenter 캐시가 새로 고쳐질 때까지 플러그인이 vCenter에 계속 표시될 수 있습니다. 그러나 플러그인이 제거되었기 때문에 해당 호스트에서 SnapCenter VMware vSphere 작업을 수행할 수 없습니다. 로컬 vCenter 캐시를 새로 고치려면 먼저 어플라이언스가 SnapCenter VMware 플러그인 구성 페이지에서 사용 안 함 상태인지 확인한 다음 vCenter 웹 클라이언트 서비스를 다시 시작합니다.
