---
sidebar: sidebar 
permalink: scpivs44_download_job_logs.html 
keywords:  
summary: SnapCenter VMware vSphere Client의 대시보드에 있는 작업 모니터 탭에서 작업 로그를 다운로드할 수 있습니다. 
---
= 작업 로그를 다운로드합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter VMware vSphere Client의 대시보드에 있는 작업 모니터 탭에서 작업 로그를 다운로드할 수 있습니다.

VMware vSphere Client를 사용하는 동안 예기치 않은 동작이 발생하는 경우 로그 파일을 사용하여 원인을 식별하고 문제를 해결할 수 있습니다.


NOTE: 작업 로그 보존의 기본값은 30일입니다. 작업 보유의 기본값은 90일입니다. 구성된 보존보다 오래된 작업 로그 및 작업은 6시간마다 삭제됩니다. 구성 REST API를 사용하여 작업 및 작업 로그가 유지되는 기간을 수정할 수 있습니다. 삭제 일정은 수정할 수 없습니다.

.단계
. vCenter Client 바로 가기 페이지에서 SnapCenter Plug-in for VMware vSphere (SCV) 를 선택합니다.
. SCV의 왼쪽 탐색 창에서 * 대시보드 * > * 작업 모니터 * 를 선택합니다.
. Job Monitor 제목 표시줄에서 다운로드 아이콘을 선택합니다.
+
아이콘을 보려면 오른쪽으로 스크롤해야 할 수도 있습니다.

+
작업을 두 번 클릭하여 작업 세부 정보 창에 액세스한 다음 * 작업 로그 다운로드 * 를 선택할 수도 있습니다.



.결과
작업 로그는 VMware vSphere용 SnapCenter 플러그인이 구축된 Linux VM 호스트에 있습니다. 기본 작업 로그 위치는 `/var/log/netapp`입니다.

작업 로그를 다운로드하려고 했지만 오류 메시지에 명명된 로그 파일이 삭제된 경우 "HTTP error 500 problem 액세스/export-scV-logs" 오류가 발생할 수 있습니다. 이 오류를 해결하려면 오류 메시지에 명명된 파일에 대한 파일 액세스 상태 및 권한을 확인하고 액세스 문제를 해결하십시오.
