---
sidebar: sidebar 
permalink: scpivs44_restore_vmdks_from_backups.html 
keywords:  
summary: 기존 VM 또는 VVOL VM의 운영 또는 보조 백업에서 기존 VMDK를 복원하거나 삭제된 VMDK 또는 분리된 VMDK를 복구할 수 있습니다. 
---
= 백업에서 VMDK 복구
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
기존 VM 또는 VVOL VM의 운영 또는 보조 백업에서 기존 VMDK를 복원하거나 삭제된 VMDK 또는 분리된 VMDK를 복구할 수 있습니다.

VM의 하나 이상의 VMDK(가상 머신 디스크)를 동일한 데이터 저장소에 복구할 수 있습니다.


TIP: NFS 환경의 복구 작업 성능을 향상시키하려면 VMware 애플리케이션 VAAI(vStorage API for Array Integration)를 설정합니다.

.시작하기 전에
* 백업이 있어야 합니다.
+
VMware vSphere용 SnapCenter 플러그인을 사용하여 VM 백업을 생성해야 합니다.

* VM이 전송 중이 아니어야 합니다.
+
복구할 VM이 vMotion 또는 Storage vMotion 상태가 아니어야 합니다.



.이 작업에 대해
* VMDK가 VM에서 삭제되거나 분리된 경우 복원 작업은 VMDK를 VM에 연결합니다.
* VM이 있는 FabricPool의 스토리지 계층을 사용할 수 없는 경우 복구 작업이 실패할 수 있습니다.
* 연결 및 복구 작업은 기본 SCSI 컨트롤러를 사용하여 VMDK에 연결합니다. NVMe 컨트롤러가 있는 VM에 연결된 VMDK는 백업되지만 연결 및 복원 작업에서는 SCSI 컨트롤러를 사용하여 다시 연결합니다.


.단계
. VMware vSphere 클라이언트 GUI의 도구 모음에서 * 메뉴 * 를 클릭한 다음 드롭다운 목록에서 * VM 및 템플릿 * 을 선택합니다.
. 왼쪽 탐색 창에서 VM을 마우스 오른쪽 버튼으로 클릭한 다음 드롭다운 목록에서 * NetApp SnapCenter * 를 선택하고 보조 드롭다운 목록에서 * 복원 * 을 선택합니다.
. 복원 * 마법사의 백업 선택 페이지에서 복원할 백업 복사본을 선택합니다.
+
특정 백업 이름 또는 부분 백업 이름을 검색하거나 필터 아이콘을 클릭하고 날짜 및 시간 범위를 선택하여 백업 목록을 필터링할 수 있습니다. 또한 VMware 스냅샷을 포함하는 백업의 마운트 여부, 및 운영 또는 2차 위치에 있습니다. 확인 * 을 클릭하여 마법사로 돌아갑니다.

. 범위 선택 * 페이지에서 복구 대상을 선택합니다.
+
|===
| 복원 대상 | 복원 대상 지정… 


| 원래 데이터 저장소입니다 | 드롭다운 목록에서 * 특정 디스크 * 를 선택한 후 * 다음 * 을 클릭합니다. 데이터스토어 선택 표에서 VMDK를 선택하거나 선택 취소할 수 있습니다. 


| 대체 위치에 있는 대체 데이터 저장소입니다 | 대상 데이터 저장소를 클릭하고 목록에서 다른 데이터 저장소를 선택합니다. 
|===
. 위치 선택 * 페이지에서 복원할 스냅샷(기본 또는 보조)을 선택합니다.
. 요약 페이지를 검토한 다음 * 마침 * 을 클릭합니다.
. 선택 사항: 화면 하단의 * Recent Tasks * 를 클릭하여 작업 진행 상황을 모니터링합니다.
. 업데이트된 정보를 표시하려면 화면을 새로 고칩니다.

