---
sidebar: sidebar 
permalink: scpivs44_manage_the_vmware_vsphere_web_client_service.html 
keywords:  
summary: SnapCenter VMware vSphere Client가 잘못 작동하기 시작하면 브라우저 캐시를 지워야 할 수 있습니다. 문제가 지속되면 VMware vSphere Client 서비스를 다시 시작합니다. 
---
= VMware vSphere Client 서비스를 다시 시작합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter VMware vSphere Client가 잘못 작동하기 시작하면 브라우저 캐시를 지워야 할 수 있습니다. 문제가 지속되면 VMware vSphere Client 서비스를 다시 시작합니다.



== Linux vCenter에서 웹 클라이언트 서비스를 다시 시작합니다

vCenter가 Linux 어플라이언스에 있는 경우 Linux 명령을 사용하여 SnapCenter VMware vSphere 클라이언트 서비스를 다시 시작해야 합니다.

.시작하기 전에
vCenter 6.5 이상을 실행해야 합니다.

.단계
. SSH를 사용하여 vCenter Server Appliance에 루트로 로그인합니다.
. 다음 명령을 사용하여 어플라이언스 셸 또는 Bash Shell에 액세스합니다.
+
'지옥'입니다

. 다음 HTML5 명령을 사용하여 웹 클라이언트 서비스를 중지합니다.
+
'Service-control--stop vSphere-UI

. 다음 HTML5 명령을 사용하여 vCenter에서 오래된 scvm 패키지를 모두 삭제합니다.
+
`etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity/rm -rf com.netapp.scv.client-<version_number>`

+

IMPORTANT: VASA 또는 vCenter 7.x 이상 패키지를 제거하지 마십시오.

. 다음 HTML5 명령을 사용하여 웹 클라이언트 서비스를 시작합니다.
+
'Service-control--start vSphere-UI'를 선택합니다


