---
sidebar: sidebar 
permalink: scpivs44_download_the_ova_open_virtual_appliance.html 
keywords:  
summary: tar 파일에는 VM 및 데이터 저장소 데이터 보호 및 인증서 파일에 대한 마이크로서비스 집합인 OVA가 포함되어 있습니다. 
---
= OVA(Open Virtual Appliance) 다운로드
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
OVA(Open Virtual Appliance)를 설치하기 전에 vCenter에 인증서를 추가합니다. tar 파일에는 OVA 및 Entrust Root 및 Intermediate 인증서가 들어 있으며 인증서는 인증서 폴더 내에 있습니다. OVA 구축은 VMware vCenter 7u1 이상에서 지원됩니다.

VMware vCenter 7.0.3 이상 버전에서는 Entrust 인증서에 의해 서명된 OVA를 더 이상 신뢰할 수 없습니다. 문제를 해결하려면 다음 절차를 수행해야 합니다.

.단계
. VMware용 SnapCenter 플러그인을 다운로드하려면 다음을 수행하십시오.
+
** NetApp Support 사이트( 에 로그인합니다 https://mysupport.netapp.com/products/index.html["https://mysupport.netapp.com/products/index.html"^])를 클릭합니다.
** 제품 목록에서 * SnapCenter Plug-in for VMware vSphere * 를 선택한 다음 * 최신 릴리스 다운로드 * 버튼을 클릭합니다.
** VMware vSphere용 SnapCenter 플러그인을 다운로드하십시오 `.tar` 파일을 원하는 위치에 저장합니다.


. vSphere Client를 사용하여 vCenter Server에 로그인합니다.
. Administration > Certificates > Certificate Management * 로 이동합니다.
. 신뢰할 수 있는 루트 저장소 * 옆에 있는 * 추가 * 를 클릭합니다
. Entrust Root 및 Intermediate 인증서의 위치를 찾아 선택합니다. 인증서는 * 신뢰할 수 있는 루트 인증서 * 아래 패널에 추가됩니다. 인증서가 설치되면 OVA를 확인하고 배포할 수 있습니다.



NOTE: 다운로드한 OVA가 변조되지 않은 경우 * Publisher * 열에 * 신뢰할 수 있는 인증서 * 가 표시됩니다.
