---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_from_vmdks.html 
keywords:  
summary: Windows 게스트 OS의 VMDK에서 하나 이상의 파일 또는 폴더를 복원할 수 있습니다. 
---
= VMDK에서 게스트 파일 및 폴더 복구
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Windows 게스트 OS의 VMDK에서 하나 이상의 파일 또는 폴더를 복원할 수 있습니다.

.이 작업에 대해
기본적으로 연결된 가상 디스크는 24시간 동안 사용할 수 있으며 자동으로 분리됩니다. 마법사에서 복구 작업이 완료되면 세션이 자동으로 삭제되도록 선택하거나 언제든지 게스트 파일 복원 세션을 수동으로 삭제하거나 * 게스트 구성 * 페이지에서 시간을 연장할 수 있습니다.

게스트 파일 또는 폴더 복원 성능은 복원할 파일 또는 폴더의 크기와 복원할 파일 또는 폴더의 수라는 두 가지 요소에 따라 달라집니다. 복원할 데이터 세트의 크기가 같은 경우 작은 크기의 파일을 복원하는 데 예상보다 많은 수의 작은 크기의 파일을 복원하는 데 시간이 오래 걸릴 수 있습니다.


IMPORTANT: 하나의 VM에서 하나의 연결 또는 복원 작업만 동시에 실행할 수 있습니다. 동일한 VM에서 병렬 연결 또는 복원 작업을 실행할 수 없습니다.


IMPORTANT: 게스트 복원 기능을 사용하면 시스템 및 숨겨진 파일을 보고 복원하며 암호화된 파일을 볼 수 있습니다. 기존 시스템 파일을 덮어쓰거나 암호화된 파일을 암호화된 폴더로 복원하지 마십시오. 복구 작업 중에 게스트 파일의 숨김, 시스템 및 암호화된 속성은 복원된 파일에 유지되지 않습니다. 예약된 파티션을 보거나 찾아보면 오류가 발생할 수 있습니다.

.단계
. Menu * 를 클릭하고 * Hosts and Clusters * 메뉴 옵션을 선택한 다음, VM을 선택하고 * NetApp SnapCenter * 를 선택한 다음 * 게스트 파일 복원 * 을 클릭합니다.
. VMware vSphere Client의 보조 드롭다운 목록에서 * 게스트 파일 복원 * 을 클릭하여 마법사를 시작합니다.
. Restore Scope * 페이지에서 연결할 가상 디스크가 포함된 백업을 지정하려면 다음을 수행합니다.
+
.. 백업 이름 * 표에서 연결할 가상 디스크가 들어 있는 백업을 선택합니다.
.. VMDK * 테이블에서 복원할 파일 또는 폴더가 포함된 가상 디스크를 선택합니다.
.. Locations* 테이블에서 연결할 가상 디스크의 위치(기본 또는 보조)를 선택합니다.


. 게스트 세부 정보 * 페이지에서 다음을 수행합니다.
+
.. 가상 디스크를 연결할 위치 선택:
+
|===
| 이 옵션을 선택합니다. | 다음과 같은 경우 


| 게스트 VM을 사용합니다  a| 
마법사를 시작하기 전에 마우스 오른쪽 단추로 클릭한 VM에 가상 디스크를 연결한 다음 마우스 오른쪽 단추로 클릭한 VM의 자격 증명을 선택합니다.


NOTE: VM에 대한 자격 증명이 이미 생성되어 있어야 합니다.



| 게스트 파일 복원 프록시 VM을 사용합니다  a| 
가상 디스크를 프록시 VM에 연결한 다음 프록시 VM을 선택합니다.


NOTE: 연결 및 복원 작업을 시작하기 전에 프록시 VM을 구성해야 합니다.

|===
.. 이메일 알림 전송 * 옵션을 선택합니다.
+
이 옵션은 연결 작업이 완료되고 가상 디스크를 사용할 수 있을 때 알림을 받으려면 필요합니다. 알림 e-메일에는 가상 디스크 이름, VM 이름 및 VMDK에 대해 새로 할당된 드라이브 문자가 포함됩니다.

+

TIP: 게스트 파일 복구는 비동기 작업이며 게스트 세션을 설정하는 데 시간이 오래 소요될 수 있으므로 이 옵션을 활성화하십시오.

+
이 옵션은 vCenter에서 VMware vSphere Client를 설정할 때 구성된 e-메일 설정을 사용합니다.



. 요약을 검토하고 * Finish * 를 클릭합니다.
+
마침 * 을 클릭하기 전에 마법사의 모든 페이지로 돌아가서 정보를 변경할 수 있습니다.

. 연결 작업이 완료될 때까지 기다립니다.
+
대시보드 작업 모니터에서 작업 진행률을 보거나 이메일 알림을 기다릴 수 있습니다.

. 연결된 가상 디스크에서 복원할 파일을 찾으려면 * 메뉴 > VMware vSphere * 용 SnapCenter 플러그인 을 클릭한 다음 왼쪽 탐색 창에서 * 게스트 파일 복원 * 을 클릭하고 * 게스트 구성 * 탭을 선택합니다.
+
Guest Session Monitor 테이블에서 *...를 클릭하여 세션에 대한 추가 정보를 표시할 수 있습니다. * 를 선택합니다.

. 알림 이메일에 나열된 가상 디스크에 대한 게스트 파일 복원 세션을 선택합니다.
+
모든 파티션에는 시스템 예약 파티션을 포함하여 드라이브 문자가 할당됩니다. VMDK에 파티션이 여러 개 있는 경우 게스트 파일 찾아보기 페이지 맨 위의 드라이브 필드에 있는 드롭다운 목록에서 드라이브를 선택하여 특정 드라이브를 선택할 수 있습니다.

. 가상 디스크의 파일 및 폴더 목록을 보려면 * 파일 찾아보기 * 아이콘을 클릭합니다.
+
폴더를 두 번 클릭하여 개별 파일을 찾아 선택할 때 파일 목록을 가져오는 동안 시간이 지연될 수 있습니다. 이 때 가져오기 작업은 런타임에 수행되기 때문입니다.

+
보다 쉬운 검색을 위해 검색 문자열에서 필터를 사용할 수 있습니다. 필터는 대소문자를 구분하며 공백 없이 Perl 식입니다. 기본 검색 문자열은 `.' * 입니다. 다음 표에서는 Perl 검색 식의 몇 가지 예를 보여 줍니다.

+
|===
| 이 표현식은… | 검색 내용 


| . | 줄 바꿈 문자를 제외한 모든 문자. 


| . * | 모든 문자열. 이것이 기본값입니다. 


| A | 문자 a. 


| 복부 | 문자열 AB. 


| a [수직 막대] b | a 또는 b 문자입니다 


| A * | a 문자의 인스턴스가 0개 이상 있습니다 


| A+ | a 문자의 하나 이상의 인스턴스 


| A? | a 문자의 인스턴스 하나 또는 0입니다 


| {x} | 문자 a의 인스턴스 수가 정확히 x 개임 


| {x,} | a 문자의 인스턴스 최소 x 개 이상 


| {x,y} | 문자 A 및 최대 y 수의 인스턴스 최소 x 개수입니다. 


| \ | 특수 문자를 이스케이프합니다. 
|===
+
게스트 파일 찾아보기 페이지에는 다른 모든 파일 및 폴더와 함께 숨겨진 모든 파일과 폴더가 표시됩니다.

. 복원하려는 파일이나 폴더를 하나 이상 선택한 다음 * 위치 복원 선택 * 을 클릭합니다.
+
복원할 파일과 폴더가 선택한 파일 테이블에 나열됩니다.

. Select Restore Location * 페이지에서 다음을 지정합니다.
+
|===
| 옵션을 선택합니다 | 설명 


| 경로로 복원합니다 | 선택한 파일이 복원될 게스트의 UNC 공유 경로를 입력합니다. IPv4 예: '\\10.60.13665\c$'IPv6 예:\\fd20-8b1e-b255-832e--61.ipv6-literal.net\C\restore` 


| 원본 파일이 있는 경우  a| 
복원할 파일 또는 폴더가 복원 대상에 이미 있는 경우 수행할 작업(항상 덮어쓰기 또는 항상 건너뛰기)을 선택합니다.


NOTE: 폴더가 이미 있으면 폴더의 내용이 기존 폴더와 병합됩니다.



| 성공적으로 복구한 후 게스트 세션 연결을 끊습니다 | 복구 작업이 완료될 때 게스트 파일 복구 세션을 삭제하려면 이 옵션을 선택합니다. 
|===
. 복원 * 을 클릭합니다.
+
대시보드 작업 모니터에서 복구 작업의 진행률을 보거나 e-메일 알림을 기다릴 수 있습니다. e-메일 알림을 보내는 데 걸리는 시간은 복원 작업이 완료되는 데 걸리는 시간에 따라 달라집니다.

+
알림 e-메일에는 복구 작업의 출력이 포함된 첨부 파일이 포함되어 있습니다. 복구 작업이 실패하면 첨부 파일을 열어 추가 정보를 확인합니다.


