---
sidebar: sidebar 
permalink: scpivs44_how_restore_operations_are_performed.html 
keywords:  
summary: 'VMFS 환경의 경우 VMware vSphere용 SnapCenter 플러그인은 Storage VMotion을 사용하여 클론 및 마운트 작업을 사용하여 복구 작업을 수행합니다. NFS 환경의 경우 플러그인은 네이티브 ONTAP SFSR(Single File SnapRestore)을 사용하여 대부분의 복구 작업에 더 높은 효율성을 제공합니다. VVOL VM의 경우 플러그인은 복원 작업에 ONTAP 단일 파일 스냅샷 복원 및 SnapMirror 복원을 사용합니다.' 
---
= 복원 작업 수행 방법
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


VMFS 환경의 경우 VMware vSphere용 SnapCenter 플러그인은 Storage VMotion을 사용하여 클론 및 마운트 작업을 사용하여 복구 작업을 수행합니다. NFS 환경의 경우 플러그인은 네이티브 ONTAP SFSR(Single File SnapRestore)을 사용하여 대부분의 복구 작업에 더 높은 효율성을 제공합니다. VVOL VM의 경우 플러그인은 복원 작업을 위해 ONTAP 단일 파일 스냅샷 복원(ONTAP SFSR) 및 SnapMirror 복원을 사용합니다. 다음 표에는 복원 작업이 수행되는 방법이 나와 있습니다.

|===
| 복원 작업 | 보낸 사람 | 를 사용하여 수행됩니다 


| VM 및 VMDK의 파일 | 기본 백업 | NFS 환경:ONTAP 단일 파일 SnapRestore VMFS 환경:Storage VMotion을 사용하여 클론 및 마운트 


| VM 및 VMDK의 파일 | 보조 백업 | NFS 환경:ONTAP 단일 파일 SnapRestore VMFS 환경:Storage VMotion을 사용하여 클론 및 마운트 


| 삭제된 VM 및 VMDK입니다 | 기본 백업 | NFS 환경:ONTAP 단일 파일 SnapRestore VMFS 환경:Storage VMotion을 사용하여 클론 및 마운트 


| 삭제된 VM 및 VMDK입니다 | 보조 백업 | NFS 환경: Storage VMotion VMFS 환경에서 복제 및 마운트: Storage VMotion을 사용하여 클론 및 마운트 


| VM 및 VMDK의 파일 | VM 정합성이 보장되는 기본 백업 | NFS 환경:ONTAP 단일 파일 SnapRestore VMFS 환경:Storage VMotion을 사용하여 클론 및 마운트 


| VM 및 VMDK의 파일 | VM 정합성이 보장되는 보조 백업입니다 | NFS 환경: Storage VMotion VMFS 환경에서 복제 및 마운트: Storage VMotion을 사용하여 클론 및 마운트 


| VVOL VM | 충돌 시에도 정합성 보장 기본 백업 | 모든 프로토콜에 대한 ONTAP 단일 파일 SnapRestore 


| VVOL VM | 충돌 시에도 정합성 보장 2차 백업 | 모든 프로토콜에 대한 ONTAP SnapMirror 복원 


| FlexGroup VM입니다 | 기본 백업  a| 
NFS 환경: * ONTAP 단일 파일 SnapRestore ONTAP 버전 9.10.1 이상을 사용하는 경우 * ONTAP 이전 버전에서 Storage VMotion을 사용하여 클론 및 마운트합니다

VMFS 환경: FlexGroups에서는 지원되지 않습니다



| FlexGroup VM입니다 | 보조 백업  a| 
NFS 환경:

* ONTAP 버전 9.10.1 이상을 사용하는 경우 ONTAP SnapMirror 복원
* ONTAP 이전 버전에 대한 Storage VMotion을 사용하여 클론 및 마운트합니다


VMFS 환경: FlexGroups에서는 지원되지 않습니다

|===

NOTE: VVOL 컨테이너 재조정 후에는 VVOL VM을 복원할 수 없습니다.

게스트 파일 복원 작업은 NFS 및 VMFS 환경 모두에서 Storage VMotion이 아닌 클론 및 마운트 작업을 사용하여 수행됩니다.


IMPORTANT: 복구 작업 중에 SCV에서 사전 복원을 호출하는 동안 "해결되지 않은 볼륨은 null임" 또는 "예외"라는 오류가 발생할 수 있습니다. 복제된 LUN을 데이터 저장소로 마운트하는 중 오류가 발생했습니다… 이 문제는 SnapCenter VMware 플러그인이 클론 재서명을 시도할 때 발생합니다. VMware 제한으로 인해 SnapCenter VMware 플러그인은 고급 ESXi 구성에서 자동 재서명 값을 제어할 수 없습니다.

오류에 대한 자세한 내용은 {link-with-bunes} [KB 문서: SCV 클론 또는 복구가 실패하고 'Host unresolved volumes is null^] 오류가 표시됩니다.
