---
sidebar: sidebar 
permalink: scpivs44_guest_file_restore_scenarios_you_might_encounter.html 
keywords:  
summary: 게스트 파일을 복구하려고 할 때 게스트 파일 복구 세션이 비어 있거나, 게스트 파일 복구 연결 디스크 작업이 실패하거나, 게스트 파일 복구 세션이 중단된 후 백업이 분리되지 않는 경우가 발생할 수 있습니다. 
---
= 발생할 수 있는 게스트 파일 복원 시나리오
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
게스트 파일을 복원하려고 할 때 다음 시나리오가 발생할 수 있습니다.



== 게스트 파일 복구 세션이 비어 있습니다

이 문제는 게스트 파일 복구 세션을 생성하고 해당 세션이 활성 상태인 동안 게스트 운영 체제가 재부팅될 때 발생합니다. 이 경우 게스트 운영 체제의 VMDK가 오프라인 상태로 유지될 수 있습니다. 따라서 게스트 파일 복구 세션을 탐색하려고 하면 목록이 비어 있습니다.

이 문제를 해결하려면 게스트 OS에서 수동으로 VMDK를 다시 온라인으로 설정합니다. VMDK가 온라인 상태이면 게스트 파일 복원 세션에 올바른 콘텐츠가 표시됩니다.



== 게스트 파일 복구 연결 디스크 작업이 실패했습니다

이 문제는 게스트 파일 복원 작업을 시작할 때 발생하지만 VMware Tools가 실행 중이고 게스트 OS 자격 증명이 올바르더라도 연결 디스크 작업이 실패합니다. 이 경우 다음 오류가 반환됩니다.

"게스트 자격 증명을 확인하는 동안 오류가 발생하여 지정된 자격 증명을 사용하여 게스트 시스템에 액세스하지 못했습니다. 시스템에서 VMware 도구가 제대로 실행되고 있는지, 사용된 계정이 관리자 계정인지 확인하십시오. 오류는 SystemError VIX 오류 코드 = (3016, 0)입니다.

이 문제를 해결하려면 게스트 OS에서 VMware Tools Windows 서비스를 다시 시작한 다음 게스트 파일 복구 작업을 다시 시도하십시오.



== 게스트 이메일이?????? 파일 이름

이 문제는 게스트 파일 복원 기능을 사용하여 이름에 영어가 아닌 문자가 있는 파일 또는 폴더를 복원할 때 발생하며 이메일 알림에 "?????? "복원한 파일 이름으로. 이메일 첨부 파일에는 복원된 파일 및 폴더의 이름이 올바르게 나열됩니다.



== 게스트 파일 복구 세션이 중단된 후에는 백업이 분리되지 않습니다

이 문제는 VM 정합성 보장 백업에서 게스트 파일 복원 작업을 수행할 때 발생합니다. 게스트 파일 복구 세션이 활성 상태인 동안 동일한 VM에 대해 다른 VM 정합성 보장 백업이 수행됩니다. 24시간 후 게스트 파일 복구 세션의 연결이 수동으로 또는 자동으로 끊기면 세션의 백업이 분리되지 않습니다.

이 문제를 해결하려면 활성 게스트 파일 복구 세션에서 연결된 VMDK를 수동으로 분리하십시오.
