---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_overview.html 
keywords:  
summary: 'Windows 게스트 OS의 가상 머신 디스크(VMDK)에서 파일 또는 폴더를 복원할 수 있습니다.' 
---
= 워크플로우, 사전 요구 사항 및 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Windows 게스트 OS의 가상 머신 디스크(VMDK)에서 파일 또는 폴더를 복원할 수 있습니다.



== 게스트 복원 워크플로우

게스트 OS 복원 작업에는 다음 단계가 포함됩니다.

. 첨부
+
가상 디스크를 게스트 VM 또는 프록시 VM에 연결하고 게스트 파일 복원 세션을 시작합니다.

. 잠깐만
+
연결 작업이 완료될 때까지 기다린 후 탐색 및 복원할 수 있습니다. 연결 시

+
작업이 완료되고 게스트 파일 복구 세션이 자동으로 생성되고 e-메일 알림이 생성됩니다

+
전송.

. 파일 또는 폴더를 선택합니다
+
게스트 파일 복원 세션에서 VMDK를 찾아보고 복구할 파일 또는 폴더를 하나 이상 선택합니다.

. 복원
+
선택한 파일 또는 폴더를 지정된 위치로 복원합니다.





== 게스트 파일 및 폴더 복구를 위한 사전 요구 사항

Windows 게스트 OS의 VMDK에서 하나 이상의 파일 또는 폴더를 복원하기 전에 모든 요구 사항을 알고 있어야 합니다.

* VMware 도구를 설치하고 실행해야 합니다.
+
SnapCenter는 VMware 툴의 정보를 사용하여 VMware 게스트 OS에 대한 연결을 설정합니다.

* Windows 게스트 OS는 Windows Server 2008 R2 이상을 실행해야 합니다.
+
지원되는 버전에 대한 최신 정보는 를 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴(IMT)"^].

* 대상 VM의 자격 증명은 기본 제공 도메인 관리자 계정 또는 기본 제공 로컬 관리자 계정을 지정해야 합니다. 사용자 이름은 "관리자"여야 합니다. 복구 작업을 시작하기 전에 가상 디스크를 연결할 VM에 대해 자격 증명을 구성해야 합니다. 연결 작업과 후속 복구 작업 모두에 자격 증명이 필요합니다. 작업 그룹 사용자는 기본 제공 로컬 관리자 계정을 사용할 수 있습니다.
+

IMPORTANT: 기본 제공 관리자 계정이 아닌 VM 내에 관리 권한이 있는 계정을 사용해야 하는 경우 게스트 VM에서 UAC를 비활성화해야 합니다.

* 복원할 백업 스냅샷과 VMDK를 알고 있어야 합니다.
+
VMware vSphere용 SnapCenter 플러그인은 복구할 파일 또는 폴더 검색을 지원하지 않습니다. 따라서 시작하기 전에 스냅샷 및 해당 VMDK와 관련된 파일 또는 폴더의 위치를 알아야 합니다.

* 연결할 가상 디스크가 SnapCenter 백업에 있어야 합니다.
+
복구할 파일 또는 폴더가 포함된 가상 디스크는 VMware vSphere용 SnapCenter 플러그인용 가상 어플라이언스를 사용하여 수행된 VM 백업에 있어야 합니다.

* 프록시 VM을 사용하려면 프록시 VM을 구성해야 합니다.
+
가상 디스크를 프록시 VM에 연결하려면 연결 및 복원 작업이 시작되기 전에 프록시 VM을 구성해야 합니다.

* 영어 이외의 알파벳 이름이 있는 파일의 경우 단일 파일이 아닌 디렉터리에 저장해야 합니다.
+
일본어 간지 등의 영문자가 아닌 이름으로 파일을 복원할 수 있습니다.

* Linux 게스트 OS에서 복구는 지원되지 않습니다
+
Linux 게스트 OS를 실행 중인 VM에서는 파일과 폴더를 복원할 수 없습니다. 그러나 VMDK를 첨부한 다음 파일과 폴더를 수동으로 복원할 수 있습니다. 지원되는 게스트 OS에 대한 최신 정보는 를 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴(IMT)"^].





== 게스트 파일 복구 제한 사항

게스트 OS에서 파일 또는 폴더를 복구하기 전에 이 기능이 지원하지 않는 기능에 대해 알고 있어야 합니다.

* 게스트 OS 내에서 동적 디스크 유형을 복원할 수 없습니다.
* 암호화된 파일이나 폴더를 복원하면 암호화 속성이 유지되지 않습니다. 파일 또는 폴더를 암호화된 폴더로 복원할 수 없습니다.
* 게스트 파일 찾아보기 페이지에는 필터링할 수 없는 숨겨진 파일 및 폴더가 표시됩니다.
* Linux 게스트 OS에서 복원할 수 없습니다.
+
Linux 게스트 OS를 실행 중인 VM에서는 파일과 폴더를 복원할 수 없습니다. 그러나 VMDK를 첨부한 다음 파일과 폴더를 수동으로 복원할 수 있습니다. 지원되는 게스트 OS에 대한 최신 정보는 를 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴(IMT)"^].

* NTFS 파일 시스템에서 FAT 파일 시스템으로 복원할 수 없습니다.
+
NTFS 형식에서 FAT 형식으로 복원하려고 하면 FAT 파일 시스템은 Windows 보안 특성을 지원하지 않으므로 NTFS 보안 설명자가 복사되지 않습니다.

* 클론 생성된 VMDK 또는 초기화되지 않은 VMDK에서 게스트 파일을 복원할 수 없습니다.
* ONTAP 9.2 이상을 실행하는 시스템에서 백업을 수행하고 VMware 정합성 보장 옵션이 켜져 있는 경우 보조 백업에서 복원할 수 없습니다.
* 파일의 디렉토리 구조는 복원할 수 없습니다.
+
중첩 디렉토리의 파일을 복원하도록 선택하면 파일이 동일한 디렉토리 구조로 복원되지 않습니다. 디렉토리 트리가 복구되지 않고 파일만 복구됩니다. 디렉터리 트리를 복원하려면 구조의 맨 위에 있는 디렉터리 자체를 복사할 수 있습니다.

* VVol VM에서 대체 호스트로 게스트 파일을 복원할 수 없습니다.
* 암호화된 게스트 파일은 복원할 수 없습니다.

