---
sidebar: sidebar 
permalink: scpivs44_overview_of_different_snapcenter_guis.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere 다른 SnapCenter 플러그인과 다른 독립형 플러그인입니다.  VM, VMDK 및 데이터 저장소에 대한 모든 백업 및 복원 작업에는 vCenter의 VMware vSphere 클라이언트 사용자 인터페이스를 사용해야 합니다. 
---
= 다양한 SnapCenter 사용자 인터페이스 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter 환경에서는 적절한 사용자 인터페이스를 사용하여 데이터 보호 및 관리 작업을 수행해야 합니다.

SnapCenter Plug-in for VMware vSphere 다른 SnapCenter 플러그인과 다른 독립형 플러그인입니다.  VM, VMDK 및 데이터 저장소에 대한 모든 백업 및 복원 작업에는 vCenter의 VMware vSphere 클라이언트 사용자 인터페이스를 사용해야 합니다.  또한 웹 클라이언트 사용자 인터페이스 대시보드를 사용하여 보호된 VM과 보호되지 않은 VM 목록을 모니터링할 수 있습니다.  백업 및 복원, 작업 모니터링과 같은 다른 모든 SnapCenter 플러그인(애플리케이션 기반 플러그인) 작업의 경우 SnapCenter 사용자 인터페이스를 사용합니다.

VM과 데이터 저장소를 보호하려면 VMware vSphere 클라이언트 인터페이스를 사용합니다.  웹 클라이언트 사용자 인터페이스는 스토리지 시스템의 NetApp 스냅샷 기술과 통합됩니다.  이를 통해 몇 초 만에 VM과 데이터 저장소를 백업하고 ESXi 호스트를 오프라인으로 전환하지 않고도 VM을 복원할 수 있습니다.

SnapCenter Plug-in for VMware vSphere 에서 관리 작업을 수행하기 위한 관리 사용자 인터페이스도 있습니다.

다음 표는 SnapCenter 사용자 인터페이스가 수행하는 작업을 보여줍니다.

|===
| 이 사용자 인터페이스를 사용하세요… | 이러한 작업을 수행하려면... | 그리고 이 백업에 액세스하려면... 


| SnapCenter vSphere 클라이언트 사용자 인터페이스 | VM 및 데이터 저장소 백업 VMDK 연결 및 분리 데이터 저장소 마운트 및 VM 및 VMDK 복구 게스트 파일 및 폴더 복구 마운트 해제 | VMware vSphere 클라이언트 사용자 인터페이스를 사용하여 VM 및 데이터 저장소를 백업합니다. 


| SnapCenter 사용자 인터페이스 | Microsoft SQL Server, Microsoft Exchange 및 Oracle용 데이터베이스 보호를 비롯하여 VM에서 데이터베이스 및 애플리케이션의 백업 및 복원 데이터베이스 클론 | SnapCenter 사용자 인터페이스를 사용하여 백업을 수행합니다. 


| SnapCenter Plug-in for VMware vSphere | 네트워크 구성 수정 지원 번들 생성 NTP 서버 설정 수정 플러그인 비활성화/활성화 | 해당 없음 


| vCenter 사용자 인터페이스 | vCenter Active Directory 사용자에게 SCV 역할 추가 사용자 또는 그룹에 리소스 액세스 권한을 추가합니다 | 해당 없음 
|===
VM 일관성 백업 및 복원 작업의 경우 VMware vSphere 클라이언트 사용자 인터페이스를 사용해야 합니다.  예를 들어, 데이터스토어를 마운트하거나 이름을 바꾸는 등 VMware 도구를 사용하여 일부 작업을 수행할 수는 있지만, 이러한 작업은 SnapCenter 저장소에 등록되지 않으며 인식되지 않습니다.

SnapCenter 데이터베이스와 VM의 단일 스냅샷을 함께 지원하지 않습니다.  VM과 데이터베이스에 대한 백업은 독립적으로 예약하고 실행해야 하므로 데이터베이스와 VM이 동일한 볼륨에 호스팅되어 있더라도 별도의 스냅샷이 생성됩니다.  애플리케이션 기반 백업은 SnapCenter 사용자 인터페이스를 사용하여 예약해야 하고, VM 일관성 백업은 VMware vSphere 클라이언트 사용자 인터페이스를 사용하여 예약해야 합니다.
