---
sidebar: sidebar 
permalink: scpivs44_mount_a_backup.html 
keywords:  
summary: 백업의 파일에 액세스하려는 경우 백업에서 기존 데이터 저장소를 마운트할 수 있습니다. 백업이 생성된 동일한 ESXi 호스트에 백업을 마운트하거나 VM 및 호스트 구성이 동일한 대체 ESXi 호스트에 백업을 마운트할 수 있습니다. 데이터 저장소를 호스트에 여러 번 마운트할 수 있습니다. 
---
= 백업을 마운트합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
백업의 파일에 액세스하려는 경우 백업에서 기존 데이터 저장소를 마운트할 수 있습니다. 백업이 생성된 동일한 ESXi 호스트에 백업을 마운트하거나 VM 및 호스트 구성이 동일한 대체 ESXi 호스트에 백업을 마운트할 수 있습니다. 데이터 저장소를 호스트에 여러 번 마운트할 수 있습니다.

VVOL 데이터 저장소는 마운트할 수 없습니다.

.시작하기 전에
* 대체 ESXi 호스트가 스토리지에 접속할 수 있는지 확인합니다
+
대체 ESXi 호스트에 마운트하려면 대체 ESXi 호스트가 스토리지에 접속할 수 있고 다음이 있는지 확인해야 합니다. ** 원래 호스트의 UID 및 GID와 동일한 UID 및 GID ** VMware vSphere용 SnapCenter 플러그인용 동일한 가상 어플라이언스 버전이 원래 호스트의 가상 어플라이언스와 동일합니다

* 스토리지 이니시에이터를 ESXi에 매핑합니다
+
스토리지 시스템의 이니시에이터가 ESXi에 매핑되었는지 확인합니다.

* 오래된 LUN을 정리합니다
+
ESXi는 데이터 저장소당 하나의 고유한 LUN만 검색할 수 있으므로 둘 이상의 LUN을 찾을 경우 작업이 실패합니다. 이 문제는 이전 마운트 작업이 완료되기 전에 마운트 작업을 시작하거나 LUN을 수동으로 클론하거나 마운트 해제 작업 중에 클론이 스토리지에서 삭제되지 않은 경우에 발생할 수 있습니다. 여러 클론을 검색할 수 없도록 스토리지의 오래된 LUN을 모두 정리해야 합니다.



.이 작업에 대해
데이터 저장소가 있는 FabricPool의 스토리지 계층을 사용할 수 없는 경우 마운트 작업이 실패할 수 있습니다.

.단계
. VMware vSphere Client의 도구 모음에서 * Menu * 를 클릭한 다음 드롭다운 목록에서 * Storage * 를 선택합니다.
. 데이터 저장소를 마우스 오른쪽 버튼으로 클릭하고 드롭다운 목록에서 * NetApp SnapCenter * 를 선택한 다음 보조 드롭다운 목록에서 * 백업 마운트 * 를 선택합니다.
. 데이터 저장소 마운트 * 페이지에서 백업 및 백업 위치(운영 또는 보조)를 선택한 다음 * 마침 * 을 클릭합니다.
. 선택 사항: 데이터 저장소가 마운트되었는지 확인하려면 다음을 수행하십시오.
+
.. 도구 모음에서 * 메뉴 * 를 클릭한 다음 드롭다운 목록에서 * 저장소 * 를 선택합니다.
.. 왼쪽 탐색 창에는 목록 맨 위에 마운트한 데이터 저장소가 표시됩니다.
+
SnapVault 스케줄로 보호되고 ONTAP 8.3을 실행 중인 SnapVault 대상 볼륨에 연결 또는 마운트 작업을 수행하는 경우 연결 또는 마운트 대화 상자 화면에 추가 스냅샷이 표시될 수 있습니다. 이 문제는 연결 또는 마운트 작업에서 SnapVault 대상 볼륨을 클론하고 ONTAP에서 새 스냅샷을 생성하여 볼륨을 업데이트하기 때문에 발생합니다.

+
볼륨을 클론 복제할 때 새 스냅샷이 생성되지 않도록 하려면 SnapVault 볼륨에 대한 ONTAP 스케줄을 해제합니다. 이전의 기존 스냅샷은 삭제되지 않습니다.




