---
sidebar: sidebar 
permalink: scpivs44_ontap_rbac_features_in_snapcenter.html 
keywords:  
summary: 'SnapCenter VMware 플러그인은 vCenter Server RBAC, SnapCenter RBAC(애플리케이션 기반 작업을 지원하기 위해 필요한 경우) 및 ONTAP RBAC와 함께 사용하여 특정 사용자가 특정 스토리지 시스템의 개체에 대해 수행할 수 있는 SnapCenter 작업을 결정합니다.' 
---
= VMware vSphere용 SnapCenter 플러그인의 ONTAP RBAC 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/



NOTE: ONTAP RBAC는 SnapCenter 서버 애플리케이션 정합성 보장(VMDK를 통한 애플리케이션) 작업에만 적용됩니다.

[role="lead"]
ONTAP RBAC(역할 기반 액세스 제어)를 사용하여 특정 스토리지 시스템에 대한 액세스 및 사용자가 해당 스토리지 시스템에서 수행할 수 있는 작업을 제어할 수 있습니다. SnapCenter VMware 플러그인은 vCenter Server RBAC, SnapCenter RBAC(애플리케이션 기반 작업을 지원하기 위해 필요한 경우) 및 ONTAP RBAC와 함께 사용하여 특정 사용자가 특정 스토리지 시스템의 개체에 대해 수행할 수 있는 SnapCenter 작업을 결정합니다.

SnapCenter는 사용자가 설정한 자격 증명(사용자 이름 및 암호)을 사용하여 각 스토리지 시스템을 인증하고 해당 스토리지 시스템에서 수행할 수 있는 작업을 결정합니다. SnapCenter VMware 플러그인은 각 스토리지 시스템에 대해 하나의 자격 증명 세트를 사용합니다. 이러한 자격 증명은 해당 스토리지 시스템에서 수행할 수 있는 모든 작업을 결정합니다. 즉, 개별 SnapCenter 사용자가 아니라 SnapCenter에 대한 자격 증명입니다.

ONTAP RBAC는 스토리지 시스템에 액세스하고 VM 백업과 같은 스토리지와 관련된 SnapCenter 작업을 수행하는 경우에만 적용됩니다. 특정 스토리지 시스템에 적합한 ONTAP RBAC 권한이 없는 경우 해당 스토리지 시스템에 호스팅된 vSphere 개체에 대한 작업을 수행할 수 없습니다.

각 스토리지 시스템에는 하나의 ONTAP 권한 세트가 연결되어 있습니다.

ONTAP RBAC와 vCenter Server RBAC를 모두 사용하면 다음과 같은 이점이 있습니다.

* 보안
+
관리자는 세분화된 vCenter Server 객체 레벨과 스토리지 시스템 레벨 모두에서 어떤 작업을 수행할 수 있는지 제어할 수 있습니다.

* 감사 정보
+
대부분의 경우 SnapCenter는 스토리지 시스템에 대한 감사 추적을 제공하므로 스토리지 수정을 수행한 vCenter 사용자에게 이벤트를 다시 추적할 수 있습니다.

* 사용 편의성
+
컨트롤러 자격 증명을 한 곳에서 유지 관리할 수 있습니다.


