---
sidebar: sidebar 
permalink: scpivs44_minimum_vcenter_privileges_required.html 
keywords:  
summary: VMware vSphere용 SnapCenter 플러그인 구축을 시작하기 전에 필요한 최소 vCenter 권한이 있는지 확인해야 합니다. 
---
= 최소 vCenter 권한이 필요합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware vSphere용 SnapCenter 플러그인 구축을 시작하기 전에 필요한 최소 vCenter 권한이 있는지 확인해야 합니다.



== vCenter 관리자 역할에 필요한 권한

시스템.익명 시스템.시스템.읽기 데이터 저장소.이름 바꾸기 데이터 저장소 이동.데이터 저장소 삭제.FileManagement 데이터 저장소.AllocateSpace 네트워크.Assign Host.Config.Config.Storage Host.AdvancedConfig.Config.Config.Config.Settings 호스트.Config.Settings 호스트.Local.CreateVM Host.ReconesVM Host.Local.DeleteVM.VirtualMachine.VirtualMachine.VirtualExistExistExistExistExisteMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualRecommendeConfig.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualConfig.VirtualConfig.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualConfig.VirtualRecommendeConfig.VirtualMachine.VirtualMachine.VirtualConfig.VirtualMachine.VirtualRecommendeConfig.VirtualRecommendeConfig.VirtualRecommendeConfig.VirtualMachine.VirtualRecommendecoCreate.VirtualResource.VirtualMachine.VirtualMachine.VirtualMachine.VirtualRecommendeConfig.VirtualRecommendation.VirtualMachine.VirtualMachine.VirtualRecommendation.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualReconf



== VMware vCenter용 SnapCenter 플러그인과 관련된 필수 권한

|===


| * 권한 * | * 레이블 * 


| netscV.Guest.RestoreFile입니다 | 게스트 파일 복원 


| NetApp SCV.Recovery.MountUnmount 를 참조하십시오 | 마운트/마운트 해제 


| netappSCV.Backup.DeleteBackupJob을 참조하십시오 | 리소스 그룹/백업을 삭제합니다 


| netappSCV.Configure.ConfigureStorageSystems.Delete를 참조하십시오 | 스토리지 시스템을 제거합니다 


| netappSCV.View를 참조하십시오 | 보기 


| netappSCV.Recovery.RecoverVM | VM 복구 


| NetApp SCV.Configure.ConfigureStorageSystems.AddUpdate를 참조하십시오 | 스토리지 시스템 추가/수정 


| NetApp SCV.Backup.BackupNow | 지금 백업 


| netappSCV.Guest.Configure를 참조하십시오 | 게스트 구성 


| NetApp SCV.Configure.ConfigureSnapCenterServer를 구성할 수 있습니다 | SnapCenter 서버를 구성합니다 


| NetApp SCV.Backup.Backuped가 예약됩니다 | 리소스 그룹을 생성합니다 
|===