---
sidebar: sidebar 
permalink: scpivs44_predefined_roles_packaged_with_snapcenter.html 
keywords:  
summary: vCenter Server RBAC를 사용하여 작업을 간소화하기 위해 SnapCenter VMware 플러그인은 사용자가 SnapCenter 작업을 수행할 수 있도록 사전 정의된 역할 세트를 제공합니다. 또한 읽기 전용 역할을 통해 사용자는 SnapCenter 정보를 볼 수는 있지만 작업을 수행할 수는 없습니다. 
---
= VMware vSphere용 SnapCenter 플러그인과 함께 패키지로 제공되는 사전 정의된 역할
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vCenter Server RBAC를 사용하여 작업을 간소화하기 위해 SnapCenter VMware 플러그인은 사용자가 SnapCenter 작업을 수행할 수 있도록 사전 정의된 역할 세트를 제공합니다. 또한 읽기 전용 역할을 통해 사용자는 SnapCenter 정보를 볼 수는 있지만 작업을 수행할 수는 없습니다.

사전 정의된 역할에는 필요한 SnapCenter 관련 권한과 기본 vCenter Server 권한이 모두 포함되어 있어 작업이 올바르게 완료됩니다. 또한 지원되는 모든 버전의 vCenter Server에 필요한 권한을 부여하도록 역할이 설정됩니다.

관리자는 이러한 역할을 적절한 사용자에게 할당할 수 있습니다.

SnapCenter VMware 플러그인은 vCenter 웹 클라이언트 서비스를 다시 시작하거나 설치를 수정할 때마다 이러한 역할을 기본 값(초기 권한 집합)으로 되돌립니다. SnapCenter VMware 플러그인을 업그레이드하면 사전 정의된 역할이 해당 플러그인 버전과 함께 작동하도록 자동으로 업그레이드됩니다.

다음 표와 같이 * 메뉴 > 관리 > 역할 * 을 클릭하여 vCenter GUI에서 사전 정의된 역할을 확인할 수 있습니다.

|===
| 역할 | 설명 


| SCV 관리자 | VMware vSphere 작업을 위한 모든 SnapCenter 플러그인을 수행하는 데 필요한 모든 기본 vCenter Server 및 SnapCenter별 권한을 제공합니다. 


| SCV 백업 | vSphere 객체(가상 머신 및 데이터 저장소)를 백업하는 데 필요한 모든 기본 vCenter Server 및 SnapCenter별 권한을 제공합니다. 또한 사용자는 구성 권한에 액세스할 수 있습니다. 사용자는 백업에서 복원할 수 없습니다. 


| SCV 게스트 파일 복원 | 게스트 파일 및 폴더를 복구하는 데 필요한 모든 기본 vCenter Server 및 SnapCenter 관련 권한을 제공합니다. 사용자는 VM 또는 VMDK를 복구할 수 없습니다. 


| SCV 복원 | SnapCenter VMware 플러그인을 사용하여 백업된 vSphere 객체를 복원하고 게스트 파일 및 폴더를 복구하는 데 필요한 모든 기본 vCenter Server 및 SnapCenter별 권한을 제공합니다. 또한 사용자는 구성 권한에 액세스할 수 있습니다. 사용자는 vSphere 객체를 백업할 수 없습니다. 


| SCV 보기 | 모든 SnapCenter VMware 플러그인 백업, 리소스 그룹 및 정책에 대한 읽기 전용 액세스를 제공합니다. 
|===