---
sidebar: sidebar 
permalink: scpivs44_add_a_single_vm_or_datastore_to_a_resource_group.html 
keywords:  
summary: 단일 VM 또는 데이터 저장소를 SnapCenter Plug-in for VMware vSphere에서 관리하는 기존 리소스 그룹에 빠르게 추가할 수 있습니다. 
---
= 리소스 그룹에 단일 VM 또는 데이터 저장소를 추가합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
단일 VM 또는 데이터 저장소를 SnapCenter Plug-in for VMware vSphere에서 관리하는 기존 리소스 그룹에 빠르게 추가할 수 있습니다.

.이 작업에 대해
SAN 및 NAS 데이터 저장소를 추가할 수 있지만 VSAN 또는 VVol 데이터 저장소는 추가할 수 없습니다.

.단계
. vSphere 클라이언트 사용자 인터페이스에서 도구 모음의 *메뉴*를 선택하고 추가하려는 VM이나 데이터 저장소로 이동합니다.
. 왼쪽 탐색 창에서 VM 또는 데이터 저장소를 마우스 오른쪽 버튼으로 클릭하고 보조 드롭다운 목록에서 * SnapCenter Plug-in for VMware vSphere * > * Add to Resource Group * 을 선택합니다.
+
시스템은 먼저 SnapCenter가 관리하고 선택한 VM이 있는 스토리지 시스템과 호환되는지 확인한 다음 * 리소스 그룹에 추가 * 페이지를 표시합니다. "SnapCenter 호환성 오류" 메시지가 표시되면 선택한 VM이 SnapCenter와 호환되지 않으므로 먼저 적절한 스토리지 VM을 SnapCenter에 추가해야 합니다.

. 리소스 그룹에 추가 * 페이지에서 리소스 그룹을 선택한 다음 * 확인 * 을 선택합니다.
+
확인 * 을 선택하면 시스템은 먼저 SnapCenter가 관리하고 선택한 VM 또는 데이터 저장소가 있는 스토리지와 호환되는지 확인합니다.

+
메시지가 `Selected <resource-name> is not SnapCenter compatible` 표시되면 선택한 VM 또는 데이터 저장소가 SnapCenter와 호환되지 않는 것입니다. 자세한 내용은 을 link:scpivs44_create_resource_groups_for_vms_and_datastores.html#manage-compatibility-check-failures["호환성 검사 실패 관리"] 참조하십시오.


