---
sidebar: sidebar 
permalink: scpivs44_view_status_information.html 
keywords:  
summary: vSphere Client Dashboard에서 상태 정보를 볼 수 있습니다. 상태 정보는 한 시간에 한 번 업데이트됩니다. 
---
= 상태 정보를 봅니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


vSphere Client Dashboard에서 상태 정보를 볼 수 있습니다. 상태 정보는 한 시간에 한 번 업데이트됩니다.

.단계
. vSphere 클라이언트의 왼쪽 탐색 창에서 * Dashboard * 를 클릭하고 vCenter Server를 선택한 다음 대시보드 창에서 * Status * 탭을 클릭합니다.
. 다음 표에 나열된 것처럼 개요 상태 정보를 보거나 링크를 클릭하여 자세한 내용을 확인하십시오.
+
|===
| 이 대시보드 타일… | 다음 정보를 표시합니다. 


 a| 
최근 작업 활동
 a| 
가장 최근의 백업, 복원 및 마운트 작업 3~5개

** 해당 작업에 대한 자세한 내용을 보려면 작업 ID를 클릭하십시오.
** 모든 작업에 대한 자세한 내용을 보려면 * 모두 보기 * 를 클릭하여 작업 모니터 탭으로 이동하십시오.




 a| 
작업
 a| 
선택한 기간 내에 수행된 각 작업 유형(백업, 복구 및 마운트)의 수입니다. 차트 섹션 위로 커서를 가져가면 해당 범주에 대한 자세한 정보를 볼 수 있습니다.



 a| 
최신 보호 요약
 a| 
선택한 기간 내에 운영 VM 및 보조 VM 또는 데이터 저장소의 데이터 보호 상태를 요약한 것입니다.

** 드롭다운 메뉴를 클릭하여 * VMS * 또는 * 데이터 저장소 * 를 선택합니다.
** 보조 스토리지의 경우 * SnapVault * 또는 * SnapMirror * 를 선택합니다.
** 차트 섹션 위로 커서를 가져가면 해당 범주의 VM 또는 데이터 저장소 수가 표시됩니다. Successful 범주에는 각 리소스에 대해 가장 최근의 백업이 나열됩니다.
** 구성 파일을 편집하여 기간을 변경할 수 있습니다. 기본값은 7일입니다. 자세한 내용은 을 참조하십시오 link:scpivs44_customize_your_configuration.html["구성을 사용자 지정합니다"].
** 내부 카운터는 각 기본 또는 보조 백업 후에 업데이트됩니다. 대시보드 타일은 6시간마다 새로 고쳐집니다. 새로 고침 시간은 변경할 수 없습니다. 참고: 미러 소산 보호 정책을 사용하는 경우 보호 요약의 카운터가 SnapMirror 차트가 아닌 SnapVault 요약 차트에 표시됩니다.




 a| 
구성
 a| 
SnapCenter Plug-in for VMware vSphere에서 관리하는 각 객체 유형의 총 수



 a| 
스토리지
 a| 
생성된 총 스냅샷 복사본 수, SnapVault 및 SnapMirror 스냅샷 복사본 수, 운영 및 2차 스냅샷 복사본에 사용되는 스토리지의 양입니다. 선형 그래프는 롤링 90일 동안 1차 및 2차 스토리지 소비를 일 단위로 각각 플롯합니다. 스토리지 정보는 24시간마다 오전 1시 8분에 한 번씩 업데이트됩니다 스토리지 절감액은 논리적 용량(스냅샷 복사본 절감 + 스토리지 소비)과 운영 스토리지의 물리적 용량의 비율입니다. 막대 차트는 스토리지 절약 효과를 보여 줍니다.

차트의 한 줄 위로 커서를 가져가면 상세한 일별 결과를 볼 수 있습니다.

|===

