---
sidebar: sidebar 
permalink: scpivs44_disable_and_enable_plugin.html 
keywords:  
summary: SnapCenter 데이터 보호 기능이 더 이상 필요하지 않은 경우 SnapCenter VMware 플러그인의 구성을 변경해야 합니다. 예를 들어, 테스트 환경에 플러그인을 배포한 경우 해당 환경에서 SnapCenter 기능을 사용하지 않도록 설정하고 운영 환경에서 사용하도록 설정해야 할 수 있습니다. 
---
= VMware vSphere용 SnapCenter 플러그인을 사용하지 않도록 설정하고 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


SnapCenter 데이터 보호 기능이 더 이상 필요하지 않은 경우 SnapCenter VMware 플러그인의 구성을 변경해야 합니다. 예를 들어, 테스트 환경에 플러그인을 배포한 경우 해당 환경에서 SnapCenter 기능을 사용하지 않도록 설정하고 운영 환경에서 사용하도록 설정해야 할 수 있습니다.

.시작하기 전에
* 관리자 권한이 있어야 합니다.
* 실행 중인 SnapCenter 작업이 없는지 확인합니다.


SnapCenter VMware 플러그인을 사용하지 않도록 설정하면 모든 리소스 그룹이 일시 중단되고 vCenter에서 플러그인이 확장명으로 등록되지 않습니다.

SnapCenter VMware 플러그인을 설정하면 플러그인이 vCenter의 확장으로 등록되고, 모든 리소스 그룹이 운영 모드로 전환되고, 모든 스케줄이 설정됩니다.

.단계
. 선택 사항: 새 가상 어플라이언스로 복원하려는 경우 SnapCenter VMware 플러그인 MySQL 리포지토리를 백업합니다.
+
link:scpivs44_back_up_the_snapcenter_plug-in_for_vmware_vsphere_mysql_database.html["VMware vSphere MySQL 데이터베이스용 SnapCenter 플러그인을 백업합니다"].

. https://<OVA-IP-address>:8080` 형식으로 SnapCenter VMware 플러그인 관리 GUI에 로그인합니다.
+
플러그인을 배포하면 SnapCenter VMware 플러그인의 IP가 표시됩니다.

. 왼쪽 탐색 창에서 * 구성 * 을 클릭한 다음 * 플러그인 세부 정보 * 섹션에서 서비스 옵션을 선택 취소하여 플러그인을 비활성화합니다.
. 선택 사항을 확인합니다.
+
** VM 정합성 보장 백업을 수행하기 위해 SnapCenter VMware 플러그인만 사용한 경우
+
플러그인이 비활성화되었으며 추가 작업이 필요하지 않습니다.

** SnapCenter VMware 플러그인을 사용하여 애플리케이션 정합성이 보장되는 백업을 수행한 경우
+
플러그인이 비활성화되고 추가 정리가 필요합니다.

+
... VMware vSphere에 로그인합니다.
... VM의 전원을 끕니다.
... 왼쪽 탐색 화면에서 SnapCenter VMware 플러그인(가상 어플라이언스를 배포할 때 사용한 ".ova" 파일의 이름)의 인스턴스를 마우스 오른쪽 버튼으로 클릭하고 * Delete from Disk * 를 선택합니다.
... SnapCenter에 로그인하고 vSphere 호스트를 제거합니다.





