---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere_01.html 
keywords:  
summary:  
---
= VMware vSphere용 SnapCenter 플러그인 구축
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter 기능을 사용하여 가상 머신에서 VM, 데이터 저장소 및 애플리케이션 정합성이 보장되는 데이터베이스를 보호하려면 VMware vSphere용 SnapCenter 플러그인을 구축해야 합니다.
를 클릭합니다 link:scpivs44_download_the_ova_open_virtual_appliance.html["OVA(Open Virtual Appliance) 다운로드"^] 페이지는 OVA 파일을 다운로드하는 지침을 제공합니다.

. VMware vCenter 7.0.3 이상 버전의 경우 의 단계를 따릅니다 link:scpivs44_download_the_ova_open_virtual_appliance.html["OVA(Open Virtual Appliance) 다운로드"^] vCenter로 인증서를 가져옵니다.
. 브라우저에서 VMware vSphere vCenter로 이동합니다.
+

NOTE: IPv6 주소 HTML 웹 클라이언트의 경우 Chrome 또는 Firefox를 사용해야 합니다.

. VMware vCenter Single Sign-On 페이지 * 에 로그인합니다.
. 탐색 창에서 데이터 센터, 폴더, 클러스터 또는 호스트와 같은 가상 머신의 유효한 상위 객체인 인벤토리 객체를 마우스 오른쪽 버튼으로 클릭하고 * Deploy OVF Template * 를 선택하여 VMware 구축 마법사를 시작합니다.
. OVF 템플릿 선택 * 페이지에서 '.ova' 파일(다음 표에 나열되어 있음)의 위치를 지정하고 * 다음 * 을 클릭합니다.
+
|===
| 이 마법사 페이지에서… | 이렇게 하십시오. 


| 이름과 폴더를 선택합니다 | VM 또는 vApp의 고유한 이름을 입력하고 구축 위치를 선택합니다. 


| 리소스를 선택합니다 | 배포된 VM 템플릿을 실행할 리소스를 선택합니다. 


| 세부 정보를 검토합니다 | '.ova' 템플릿 세부 정보를 확인합니다. 


| 사용권 계약 | 모든 사용권 계약에 동의합니다 * 확인란을 선택합니다. 


| 스토리지를 선택합니다 | 구축된 OVF 템플릿의 파일 저장 위치 및 방법을 정의합니다. 


| 네트워크를 선택합니다 | 소스 네트워크를 선택하고 대상 네트워크에 매핑합니다. 


| 템플릿 사용자 지정  a| 
Register to existing vcenter * 에서 vCenter 자격 증명을 입력합니다. VMware vSphere 자격 증명용 SnapCenter 플러그인 생성 * 에서 VMware vSphere 자격 증명용 SnapCenter 플러그인을 입력합니다.


NOTE: 지정한 사용자 이름과 암호를 기록해 둡니다. 나중에 VMware vSphere용 SnapCenter 플러그인 구성을 수정하려면 이러한 자격 증명을 사용해야 합니다.

네트워크 속성 설정 * 섹션에서 네트워크 정보를 입력합니다. Setup Date and Time * 섹션에서 vCenter가 위치한 시간대를 선택합니다.



| 완료 준비 완료 | 페이지를 검토하고 * Finish * 를 클릭합니다. 
|===
+

NOTE: 모든 호스트는 IP 주소로 구성되어야 합니다(FQDN 호스트 이름은 지원되지 않음). 배포 작업을 수행해도 사용자 입력의 유효성을 검사하지 않습니다.

. SnapCenter Plug-in for VMware vSphere가 구축된 VM으로 이동한 다음 * Summary * 탭을 클릭하고 * Power On * 상자를 클릭하여 VMware vSphere용 SnapCenter 플러그인을 시작합니다.
. VMware vSphere용 SnapCenter 플러그인의 전원이 켜지는 동안 배포된 VMware vSphere용 SnapCenter 플러그인을 마우스 오른쪽 단추로 클릭하고 * 게스트 OS * 를 선택한 다음 * VMware 도구 설치 * 를 클릭합니다.
+
배포를 완료하는 데 몇 분 정도 걸릴 수 있습니다. VMware vSphere용 SnapCenter 플러그인의 전원이 켜지고 VMware 툴이 설치되며 VMware vSphere용 SnapCenter 플러그인에 로그인하라는 메시지가 화면에 표시되면 구축이 성공한 것입니다.

+
화면에 VMware vSphere용 SnapCenter 플러그인이 구축된 IP 주소가 표시됩니다. IP 주소를 기록해 둡니다. VMware vSphere용 SnapCenter 플러그인 구성을 변경하려면 VMware vSphere 관리 GUI용 SnapCenter 플러그인 에 로그인해야 합니다.

. 구축 마법사에서 제공한 자격 증명을 사용하여 구축 화면에 표시된 IP 주소를 사용하여 VMware vSphere용 SnapCenter 플러그인 관리 GUI에 로그인한 다음 대시보드에서 VMware vSphere용 SnapCenter 플러그인이 vCenter에 연결되고 활성화되었는지 확인합니다.
+
형식을 사용합니다 `\https://<appliance-IP-address>:8080` 관리 GUI에 액세스합니다.

+
배포 시 설정된 admin 사용자 이름과 암호 및 유지보수 콘솔을 사용하여 생성된 MFA 토큰으로 로그인합니다.

. vCenter HTML5 클라이언트에 로그인한 다음 도구 모음에서 * 메뉴 * 를 클릭하고 * SnapCenter Plug-in for VMware vSphere * 를 선택합니다

