---
sidebar: sidebar 
permalink: scpivs44_how_restore_operations_are_performed.html 
keywords:  
summary: 'VMFS 환경의 경우 VMware vSphere용 SnapCenter 플러그인은 Storage VMotion을 사용하여 클론 및 마운트 작업을 사용하여 복구 작업을 수행합니다. NFS 환경의 경우 플러그인은 네이티브 ONTAP SFSR(Single File SnapRestore)을 사용하여 대부분의 복구 작업에 더 높은 효율성을 제공합니다. VVOL VM의 경우 플러그인에서 복원 작업에 ONTAP 단일 파일 스냅샷 복원 및 SnapMirror 복원을 사용합니다.' 
---
= 복원 작업 수행 방법
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMFS 환경의 경우 VMware vSphere용 SnapCenter 플러그인은 Storage VMotion을 사용하여 클론 및 마운트 작업을 사용하여 복구 작업을 수행합니다. NFS 환경의 경우 플러그인은 네이티브 ONTAP SFSR(Single File SnapRestore)을 사용하여 대부분의 복구 작업에 더 높은 효율성을 제공합니다. VVOL VM의 경우 플러그인에서 ONTAP 복원 작업을 위해 ONTAP SFSR(Single File Snapshot Restore) 및 SnapMirror 복원을 사용합니다. 다음 표에는 복원 작업이 수행되는 방법이 나와 있습니다.

|===
| 복원 작업 | 보낸 사람 | 를 사용하여 수행됩니다 


| VM 및 VMDK의 파일 | 기본 백업 | NFS 환경:ONTAP 단일 파일 SnapRestore VMFS 환경:Storage VMotion을 사용하여 클론 및 마운트 


| VM 및 VMDK의 파일 | 보조 백업 | NFS 환경:ONTAP 단일 파일 SnapRestore VMFS 환경:Storage VMotion을 사용하여 클론 및 마운트 


| 삭제된 VM 및 VMDK입니다 | 기본 백업 | NFS 환경:ONTAP 단일 파일 SnapRestore VMFS 환경:Storage VMotion을 사용하여 클론 및 마운트 


| 삭제된 VM 및 VMDK입니다 | 보조 백업 | NFS 환경: Storage VMotion VMFS 환경에서 복제 및 마운트: Storage VMotion을 사용하여 클론 및 마운트 


| VM 및 VMDK의 파일 | VM 정합성이 보장되는 기본 백업 | NFS 환경:ONTAP 단일 파일 SnapRestore VMFS 환경:Storage VMotion을 사용하여 클론 및 마운트 


| VM 및 VMDK의 파일 | VM 정합성이 보장되는 보조 백업입니다 | NFS 환경: ONTAP SnapMirror Restore VMFS 환경: Storage VMotion을 사용하여 복제 및 마운트 


| VVOL VM | 충돌 시에도 정합성 보장 기본 백업 | 모든 프로토콜에 대한 ONTAP 단일 파일 SnapRestore 


| VVOL VM | 충돌 시에도 정합성 보장 2차 백업 | 모든 프로토콜에 대한 ONTAP SnapMirror 복원 


| FlexGroup VM입니다 | 기본 백업  a| 
NFS 환경: * ONTAP 단일 파일 SnapRestore ONTAP 버전 9.10.1 이상을 사용하는 경우 * ONTAP 이전 버전에서 Storage VMotion을 사용하여 클론 및 마운트합니다

VMFS 환경: FlexGroups에서는 지원되지 않습니다



| FlexGroup VM입니다 | 보조 백업  a| 
NFS 환경:

* ONTAP 버전 9.10.1 이상을 사용하는 경우 ONTAP SnapMirror 복원
* ONTAP 이전 버전에 대한 Storage VMotion을 사용하여 클론 및 마운트합니다


VMFS 환경: FlexGroups에서는 지원되지 않습니다

|===

NOTE: VVOL 컨테이너 재조정 후에는 VVOL VM을 복원할 수 없습니다.

게스트 파일 복원 작업은 NFS 및 VMFS 환경 모두에서 Storage VMotion이 아닌 클론 및 마운트 작업을 사용하여 수행됩니다.


IMPORTANT: 복구 작업 중에 오류가 발생하거나 VMware vSphere용 SnapCenter 플러그인이 클론을 재서명하려고 할 때 이 오류가 발생할 수 `Host unresolved volumes is null` 있습니다. `Exception while calling pre-restore on SCV….Error mounting cloned LUN as datastore…` VMware 제한으로 인해 VMware vSphere용 SnapCenter 플러그인은 고급 ESXi 호스트 구성에서 자동 재서명 값을 제어할 수 없습니다. NVMe over TCP 및 NVMe over FC 스토리지의 경우 새 서브시스템이 추가될 때 SCV에서 컨트롤러를 동적으로 추가할 수 없습니다. 마운트 작업 전에 필요한 매핑을 만들어야 합니다.

오류에 대한 자세한 내용은 을 https://kb.netapp.com/mgmt/SnapCenter/SCV_clone_or_restores_fail_with_error_'Host_Unresolved_volumes_is_null'#["KB 문서: 'Host unresolved volumes is null"^] 참조하십시오.
