---
sidebar: sidebar 
permalink: scpivs44_rest_apis_overview.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere REST API를 사용하여 일반적인 데이터 보호 작업을 수행할 수 있습니다. 이 플러그인에는 Windows SnapCenter Swagger 웹 페이지의 Swagger 웹 페이지가 다릅니다. 
---
= 개요
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere REST API를 사용하여 일반적인 데이터 보호 작업을 수행할 수 있습니다. 이 플러그인에는 Windows SnapCenter Swagger 웹 페이지의 Swagger 웹 페이지가 다릅니다.

* VMware vSphere용 REST API를 사용하여 VM 및 데이터 저장소에 대한 다음 작업에 대해 REST API 워크플로우가 문서화되어 있습니다.
+
** 스토리지 VM 및 클러스터를 추가, 수정 및 삭제합니다
** 리소스 그룹을 생성, 수정 및 삭제합니다
** 예약된 VM과 필요 시 백업
** 기존 VM 및 삭제된 VM을 복원합니다
** VMDK 복구
** VMDK 연결 및 분리
** 데이터 저장소를 마운트하고 마운트 해제합니다
** 작업을 다운로드하고 보고서를 생성합니다
** 기본 제공 일정을 수정합니다


* VMware vSphere용 REST API에서 지원되지 않는 작업입니다
+
** 게스트 파일 복원
** SnapCenter VMware 플러그인의 설치 및 구성
** RBAC 역할 또는 액세스 권한을 사용자에게 할당합니다


* 우리라는 매개 변수
+
Uri 매개 변수는 항상 null 값을 반환합니다.

* 로그인 시간이 초과되었습니다
+
기본 시간 초과는 120분(2시간)입니다. vCenter 설정에서 다른 시간 초과 값을 구성할 수 있습니다.

* 토큰 관리
+
보안을 위해 REST API는 각 요청에 전달되고 클라이언트 검증을 위한 모든 API 호출에 사용되는 필수 토큰을 사용합니다. VMware vSphere용 REST API는 VMware 인증 API를 사용하여 토큰을 얻습니다. VMware는 토큰 관리를 제공합니다.

+
토큰을 얻으려면 '/4.1/auth/login' REST API를 사용하고 vCenter 자격 증명을 제공합니다.

* API 버전 지정
+
각 REST API 이름은 REST API가 처음 릴리스된 SnapCenter 버전 번호를 포함합니다. 예를 들어 REST API '/4.1/datastores/{moref}/backups'가 SnapCenter 4.1에서 처음 릴리즈되었습니다.

+
향후 릴리스의 REST API는 일반적으로 이전 버전과 호환되며 필요에 따라 새 기능을 수용할 수 있도록 수정됩니다.


