---
sidebar: sidebar 
permalink: scpivs44_information_not_displayed_after_upgrading_to_a_new_patch_of_the_same_release.html 
keywords:  
summary: VMware vSphere용 SnapCenter 플러그인을 동일한 릴리즈의 새 패치로 업그레이드한 후에는 대시보드 및 작업 모니터에 최근 작업 또는 기타 정보가 표시되지 않을 수 있습니다. 
---
= 동일한 릴리즈의 새 패치로 업그레이드한 후 정보가 표시되지 않습니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware vSphere용 SnapCenter 플러그인을 동일한 릴리즈의 새 패치로 업그레이드한 후에는 대시보드 및 작업 모니터에 최근 작업 또는 기타 정보가 표시되지 않을 수 있습니다.

동일한 릴리즈의 새 패치로 업그레이드하는 경우 vCenter 웹 서버에서 SnapCenter Plug-in for VMware vSphere 캐시를 지우고 업그레이드 또는 등록 전에 서버를 다시 시작해야 합니다.

플러그인 캐시를 지우지 않으면 다음 시나리오에서 최근 작업이 대시보드 및 작업 모니터에 표시되지 않습니다.

* VMware vSphere용 SnapCenter 플러그인은 vCenter를 사용하여 구축한 후 나중에 동일한 릴리즈의 패치로 업그레이드했습니다.
* SnapCenter VMware 가상 어플라이언스는 vCenter 1에 배포되었습니다. 나중에 이 SnapCenter VMware 플러그인은 새 vCenter2에 등록되었습니다. SnapCenter VMware 플러그인의 새 인스턴스는 패치를 통해 생성되고 vCenter1에 등록됩니다. 그러나 vCenter1은 여전히 패치 없이 첫 번째 SnapCenter VMware 플러그인의 캐시된 플러그인을 가지고 있으므로 캐시를 지워야 합니다.


캐시는 서버 운영 체제의 유형에 따라 다음 위치에 있습니다.

* Windows용 vCenter Server
+
'C:\ProgramData\VMware\vCenterServer\cfg\vSphere-client\VC-packages\vSphere-client-serenity\'

* vCenter Server Linux 어플라이언스
+
'/etc/vmware/vsphere-client/vc-packages/vsphere-client-environment/'

* Windows OS
+
'%ProgramFiles%/VMware/vSphere Web Client/VC-packages/vSphere-client-enesity/'





== 해결 방법 캐시를 지우기 전에 이미 업그레이드한 경우

. SnapCenter VMware 플러그인 관리 GUI에 로그인합니다.
+
SnapCenter VMware 플러그인을 구축하면 IP가 표시됩니다.

. 왼쪽 탐색 창에서 * 구성 * 을 클릭한 다음 * 플러그인 세부 정보 * 섹션에서 서비스 옵션을 클릭하여 플러그인을 비활성화합니다.
+
SnapCenter VMware 플러그인 서비스가 비활성화되고 vCenter에서 확장이 등록되지 않았습니다.

. vSphere-client-en레니티 폴더를 찾은 후 com.netapp.scvm.webclient-<release-number>` 폴더를 찾아 삭제합니다.
+
각 릴리즈에 대한 폴더 이름이 변경됩니다.

. vCenter Server를 다시 시작합니다.
. VMware vSphere 웹 클라이언트에 로그인합니다.
. 왼쪽 탐색 창에서 * 구성 * 을 클릭한 다음 * 플러그인 세부 정보 * 섹션에서 서비스 옵션을 클릭하여 플러그인을 활성화합니다.
+
SnapCenter VMware 플러그인 서비스가 설정되고 확장 기능이 vCenter에 등록됩니다.


