---
sidebar: sidebar 
permalink: scpivs44_register_snapcenter_plugin_vmware_vsphere_with_snapcenter_server.html 
keywords:  
summary: 'SnapCenter(가상화된 데이터베이스 및 파일 시스템에 대한 애플리케이션 기반 보호 워크플로우)에서 VMDK를 넘는 애플리케이션 워크플로우를 수행하려면 SnapCenter 서버에 VMware vSphere용 SnapCenter 플러그인을 등록해야 합니다.' 
---
= VMware vSphere용 SnapCenter 플러그인을 SnapCenter 서버에 등록합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter(가상화된 데이터베이스 및 파일 시스템에 대한 애플리케이션 기반 보호 워크플로우)에서 VMDK를 넘는 애플리케이션 워크플로우를 수행하려면 SnapCenter 서버에 VMware vSphere용 SnapCenter 플러그인을 등록해야 합니다.

SnapCenter 사용자인 경우 SnapCenter 4.2로 업그레이드하고 VMware용 SnapCenter 플러그인으로 VMDK 백업을 마이그레이션한 경우 마이그레이션 명령은 플러그인을 자동으로 등록합니다.

.시작하기 전에
* SnapCenter 서버 4.2 이상을 실행해야 합니다.
* VMware vSphere용 SnapCenter 플러그인을 구축 및 활성화해야 합니다.


.이 작업에 대해
* SnapCenter GUI를 사용하여 "vSphere" 유형 호스트를 추가하여 SnapCenter 서버에 VMware vSphere용 SnapCenter 플러그인을 등록합니다.
+
포트 8144는 VMware vSphere용 SnapCenter 플러그인 내의 통신에 대해 미리 정의되어 있습니다.

+
동일한 SnapCenter 서버 4.2에서 SnapCenter vSphere용 플러그인의 여러 인스턴스를 등록하여 VM에서 애플리케이션 기반 데이터 보호 작업을 지원할 수 있습니다. 여러 SnapCenter Server에서 동일한 VMware vSphere용 SnapCenter 플러그인을 등록할 수 없습니다.

* 연결된 모드의 vCenter의 경우 각 vCenter에 대해 VMware vSphere용 SnapCenter 플러그인을 등록해야 합니다.


.단계
. SnapCenter GUI 왼쪽 탐색 창에서 * 호스트 * 를 선택합니다.
. 맨 위에 * Managed Hosts * 탭이 선택되어 있는지 확인한 다음 가상 어플라이언스 호스트 이름을 찾아 SnapCenter 서버에서 확인합니다.
. 마법사를 시작하려면 * 추가 * 를 선택하십시오.
. 다음 표에 나열된 대로 * 호스트 추가 * 대화 상자에서 SnapCenter 서버에 추가할 호스트를 지정합니다.
+
|===
| 이 필드의 경우… | 이렇게 하십시오. 


| 호스트 유형 | 호스트 유형으로 * vSphere * 를 선택합니다. 


| 호스트 이름입니다 | 가상 어플라이언스의 IP 주소를 확인합니다. 


| 자격 증명 | 구축 중에 제공된 VMware vSphere용 SnapCenter 플러그인의 사용자 이름 및 암호를 입력합니다. 
|===
. 제출 * 을 선택합니다.
+
VM 호스트가 성공적으로 추가되면 Managed Hosts 탭에 표시됩니다.

. 왼쪽 탐색 창에서 * Settings * 를 선택한 다음 * Credential * 탭을 선택하고 * Add * 를 선택하여 가상 어플라이언스에 대한 자격 증명을 추가합니다.
. VMware vSphere용 SnapCenter 플러그인을 구축하는 동안 지정된 자격 증명 정보를 제공합니다.
+

NOTE: 인증 필드에 Linux를 선택해야 합니다.



.작업을 마친 후
VMware vSphere용 SnapCenter 플러그인 자격 증명이 수정된 경우 SnapCenter 관리 호스트 페이지를 사용하여 SnapCenter 서버에서 등록을 업데이트해야 합니다.
