---
sidebar: sidebar 
permalink: scpivs44_restore_deleted_vms_from_backups.html 
keywords:  
summary: 삭제된 VM을 데이터 저장소 운영 또는 보조 백업에서 선택한 ESXi 호스트로 복구할 수 있습니다. 
---
= 백업에서 삭제된 VM을 복원합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
삭제된 VM을 데이터 저장소 운영 또는 보조 백업에서 선택한 ESXi 호스트로 복구할 수 있습니다.

다음 위치로 VM을 복원할 수 있습니다.

* 원래 위치로 복원합니다
+
** 원래 ESXi 호스트에 마운트된 원래 데이터 저장소에 마운트(VM 복제본 생성)


* 대체 위치로 복원합니다
+
** 원래 ESXi 호스트에 마운트된 다른 데이터 저장소로
** 동일한 vCenter에서 관리되는 다른 ESXi 호스트에 마운트된 원래 데이터 저장소에 대한 데이터 저장소입니다
** 동일한 vCenter에서 관리되는 다른 ESXi 호스트에 마운트된 다른 데이터 저장소에 대한 데이터 저장소입니다
** 연결된 모드에서 다른 vCenter에서 관리하는 다른 ESXi 호스트에 마운트된 다른 데이터 저장소에 대한 데이터 저장소입니다





NOTE: 다른 위치로 복구할 경우 복구 작업의 대상인 연결된 vCenter에서 VMware vSphere용 SnapCenter 플러그인이 실행되고 있어야 합니다. 대상 데이터 저장소에 충분한 공간이 있어야 합니다.


NOTE: 삭제된 VM을 복원할 때 원래 VM에 할당된 태그나 폴더는 복원되지 않습니다.

.시작하기 전에
* VMware vSphere 웹 클라이언트의 스토리지 시스템 페이지에 있는 스토리지 시스템의 사용자 계정에 가 있어야 합니다 link:scpivs44_minimum_ontap_privileges_required.html["ONTAP에 필요한 최소 ONTAP 권한"].
* vCenter의 사용자 계정에 가 있어야 합니다 link:scpivs44_minimum_vcenter_privileges_required.html["VMware vSphere용 SnapCenter 플러그인에 필요한 최소 vCenter 권한"].
* 백업이 있어야 합니다.
+
VMware vSphere용 SnapCenter 플러그인을 사용하여 VM의 백업을 생성해야 해당 VM의 VMDK를 복구할 수 있습니다.




TIP: NFS 환경의 복구 작업 성능을 향상시키하려면 VMware 애플리케이션 VAAI(vStorage API for Array Integration)를 설정합니다.

데이터 저장소를 복구할 수는 없지만 데이터 저장소의 VM을 복구할 수는 있습니다.

VM이 있는 FabricPool의 스토리지 계층을 사용할 수 없는 경우 복구 작업이 실패할 수 있습니다.

.단계
. Menu * 를 클릭하고 * Storage * 메뉴 옵션을 선택한 다음 데이터 저장소를 선택한 다음 * Configure * 탭을 선택하고 * SnapCenter Plug-in for VMware vSphere * 섹션에서 * Backups * 를 클릭합니다.
. 백업을 두 번 클릭하여 백업에 포함된 모든 VM 목록을 표시합니다.
. 백업 목록에서 삭제된 VM을 선택하고 * 복원 * 을 클릭합니다.
. 복원 * 마법사의 * 백업 선택 * 페이지에서 복원할 백업 복사본을 선택합니다.
+
특정 백업 이름 또는 부분 백업 이름을 검색하거나 필터 아이콘을 클릭하고 날짜 및 시간 범위를 선택하고 VMware 스냅샷을 포함하는 백업 여부, 마운트된 백업 여부 및 위치를 선택하여 백업 목록을 필터링할 수 있습니다. 확인 * 을 클릭하여 마법사로 돌아갑니다.

. 범위 선택 * 페이지의 * 범위 * 필드에서 * 전체 가상 머신 * 을 선택한 다음 복구 위치를 선택하고 백업을 마운트할 대상 ESXi 정보를 입력합니다.
+
복구 대상은 SnapCenter에 추가된 ESXi 호스트일 수 있습니다. 이 옵션은 VM이 지정된 시간 및 날짜의 스냅샷 복사본에서 상주하는 선택한 백업의 컨텐츠를 복원합니다. 이 옵션을 선택하면 * Restart VM *(VM 다시 시작 *) 확인란이 선택되어 있고 VM의 전원이 켜집니다.

+
NFS 데이터 저장소의 VM을 ESXi 클러스터에 있는 대체 ESXi 호스트에 복구하는 경우 VM이 복구된 후 대체 호스트에 등록됩니다.

. 위치 선택 * 페이지에서 복원할 백업 위치(기본 또는 보조)를 선택합니다.
. 요약 페이지를 검토한 다음 * 마침 * 을 클릭합니다.

