---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: 백업 리소스 그룹을 생성, 수정 및 삭제하고 리소스 그룹에 대한 백업 작업을 수행할 수 있습니다. 
---
= 자원 그룹을 관리합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
백업 리소스 그룹을 생성, 수정 및 삭제하고 리소스 그룹에 대한 백업 작업을 수행할 수 있습니다.


NOTE: 리소스 그룹을 VSC(가상 스토리지 콘솔)에서 백업 작업이라고 합니다.



== 자원 그룹에 대한 작업을 일시 중지하고 다시 시작합니다

자원 그룹에서 예약된 작업을 시작하는 것을 일시적으로 해제할 수 있습니다. 나중에 원하는 경우 이러한 작업을 활성화할 수 있습니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 * 리소스 그룹 * 을 클릭한 다음 리소스 그룹을 마우스 오른쪽 단추로 클릭하고 * 일시 중단 * 을 클릭합니다(또는 * 재시작 * 클릭).
. 확인 상자에서 * 확인 * 을 클릭하여 확인합니다.


.작업을 마친 후
자원 그룹 페이지에서 일시 중단된 자원의 작업 상태는 "Under_Maintenance"입니다. 작업 상태 열을 보려면 테이블 오른쪽으로 스크롤해야 할 수 있습니다.

백업 작업이 재개되면 작업 상태가 운영 상태로 변경됩니다.



== 리소스 그룹을 수정합니다

vCenter의 리소스 그룹에서 리소스를 제거 또는 추가하거나 정책을 분리 또는 첨부하거나 스케줄을 수정하거나 다른 리소스 그룹 옵션을 수정할 수 있습니다.

.이 작업에 대해
리소스 그룹의 이름을 수정하려면 VM, 데이터 저장소, 정책, 백업 또는 리소스 그룹 이름에 다음 특수 문자를 사용하지 마십시오.

%& * $#@! /: *? "<>-|;',.

밑줄 문자(_)를 사용할 수 있습니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 * 리소스 그룹 * 을 클릭한 다음 리소스 그룹을 선택하고 * 편집 * 을 클릭합니다.
. 리소스 그룹 편집 * 마법사의 왼쪽 목록에서 수정할 범주를 클릭하고 변경 내용을 입력합니다.
+
여러 범주에서 변경할 수 있습니다.

. 요약 페이지가 나타날 때까지 * 다음 * 을 클릭한 다음 * 마침 * 을 클릭합니다.




== 리소스 그룹을 삭제합니다

리소스 그룹의 리소스를 더 이상 보호할 필요가 없는 경우 vCenter에서 리소스 그룹을 삭제할 수 있습니다. vCenter에서 VMware vSphere용 SnapCenter 플러그인을 제거하려면 먼저 모든 리소스 그룹이 삭제되었는지 확인해야 합니다.

.이 작업에 대해
모든 리소스 그룹 삭제 작업은 강제 삭제로 수행됩니다. 삭제 작업을 수행하면 vCenter 리소스 그룹에서 모든 정책이 분리되고, VMware vSphere용 SnapCenter 플러그인에서 리소스 그룹이 제거되며, 리소스 그룹의 모든 백업과 스냅샷이 삭제됩니다.


NOTE: SnapVault 관계에서는 마지막 스냅샷을 삭제할 수 없으므로 리소스 그룹을 삭제할 수 없습니다. SnapVault 관계에 포함된 리소스 그룹을 삭제하기 전에 OnCommand System Manager를 사용하거나 ONTAP CLI를 사용하여 SnapVault 관계를 제거해야 하며 마지막 스냅샷을 삭제해야 합니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 * 리소스 그룹 * 을 클릭한 다음 리소스 그룹을 선택하고 * 삭제 * 를 클릭합니다.
. Delete resource group *(리소스 그룹 삭제 *) 확인 상자에서 * OK * 를 클릭하여 확인합니다.

