---
sidebar: sidebar 
permalink: scpivs44_restore_vms_from_backups.html 
keywords:  
summary: VM을 복원할 때 선택한 백업 복사본으로 기존 콘텐츠를 덮어쓰거나 VM의 복사본을 만들 수 있습니다. 
---
= 백업에서 VM을 복원합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VM을 복원할 때 선택한 백업 복사본으로 기존 콘텐츠를 덮어쓰거나 VM의 복사본을 만들 수 있습니다.

다음 위치로 VM을 복원할 수 있습니다.

* 원래 위치로 복원합니다
+
** 원래 ESXi 호스트에 마운트된 원래 데이터 저장소에 마운트(원래 VM을 덮어씀)


* 대체 위치로 복원합니다
+
** 원래 ESXi 호스트에 마운트된 다른 데이터 저장소로
** 동일한 vCenter에서 관리되는 다른 ESXi 호스트에 마운트된 원래 데이터 저장소에 대한 데이터 저장소입니다
** 동일한 vCenter에서 관리되는 다른 ESXi 호스트에 마운트된 다른 데이터 저장소에 대한 데이터 저장소입니다
** 연결된 모드에서 다른 vCenter에서 관리하는 다른 ESXi 호스트에 마운트된 다른 데이터 저장소에 대한 데이터 저장소입니다





NOTE: VVOL VM을 대체 호스트로 복원할 수 없습니다.


NOTE: 다음 복원 워크플로는 지원되지 않습니다. 스토리지 VM을 추가한 다음 해당 VM의 백업을 수행한 다음 스토리지 VM을 삭제하고 해당 스토리지 VM이 포함된 클러스터를 추가한 다음 원래 백업을 복원하려고 시도합니다.


TIP: NFS 환경의 복구 작업 성능을 향상시키하려면 VMware 애플리케이션 VAAI(vStorage API for Array Integration)를 설정합니다.

.시작하기 전에
* 백업이 있어야 합니다.
+
VM을 복구하려면 먼저 VMware vSphere용 SnapCenter 플러그인을 사용하여 VM 백업을 생성해야 합니다.

+

NOTE: SnapCenter Plug-in for VMware vSphere 이외의 소프트웨어로 수행된 VM의 스냅샷이 있는 경우 복구 작업을 완료할 수 없습니다.

* 대상 데이터 저장소가 준비되어 있어야 합니다.
+
** 복구 작업을 위한 대상 데이터 저장소에는 모든 VM 파일(예: vmdk, vmx, vmsd)의 복제본을 수용할 수 있는 충분한 공간이 있어야 합니다.
** 대상 데이터 저장소에 이전 복원 작업 실패의 오래된 VM 파일이 포함되어서는 안 됩니다. 오래된 파일의 이름 형식은 RESTORE_xxx_xxxxxx_<파일 이름>'입니다.


* VM이 전송 중이 아니어야 합니다.
+
복구할 VM이 vMotion 또는 Storage vMotion 상태가 아니어야 합니다.

* HA 구성 오류
+
백업을 다른 위치로 복구하기 전에 vCenter ESXi 호스트 요약 화면에 표시되는 HA 구성 오류가 없는지 확인합니다.

* 다른 위치로 복구 중입니다
+
** 다른 위치로 복구하는 경우 VMware vSphere용 SnapCenter 플러그인이 복구 작업의 대상인 vCenter에서 실행 중이어야 합니다. 대상 데이터 저장소에 충분한 공간이 있어야 합니다.
** 대체 위치로 복구 필드의 대상 vCenter는 DNS 확인이 가능해야 합니다.




.이 작업에 대해
* VM이 등록 취소되어 다시 등록되었습니다
+
VM에 대한 복구 작업은 원래 VM의 등록을 취소하고 백업 스냅샷에서 VM을 복원하며 복원된 VM을 동일한 ESXi 서버에 동일한 이름 및 구성으로 등록합니다. 복구 후 리소스 그룹에 VM을 수동으로 추가해야 합니다.

* 데이터 저장소 복원 중
+
데이터 저장소를 복구할 수는 없지만 데이터 저장소의 VM을 복구할 수는 있습니다.

* VVol VM 복원
+
** VM을 확장하는 VVOL 데이터 저장소는 지원되지 않습니다. VM의 연결된 VMDK는 VVOL 데이터 저장소에 백업되지 않으므로 복원된 VM에는 부분 VMDK만 포함됩니다.
** VVOL을 대체 호스트로 복원할 수 없습니다.
** VVOL 자동 재조정은 지원되지 않습니다.


* VM에 대한 VMware 정합성 보장 스냅샷 장애가 발생했습니다
+
VM에 대한 VMware 정합성 보장 스냅샷이 실패하더라도 VM은 백업됩니다. 복구 마법사에서 백업 복사본에 포함된 엔터티를 보고 복구 작업에 사용할 수 있습니다.

* VM이 있는 FabricPool의 스토리지 계층을 사용할 수 없는 경우 복구 작업이 실패할 수 있습니다.


.단계
. VMware vSphere Client GUI의 도구 모음에서 * 메뉴 * 를 선택한 다음 드롭다운 목록에서 * VM 및 템플릿 * 을 선택합니다.
+

NOTE: 삭제된 VM을 복구하는 경우 SnapCenter Plug-in for VMware vSphere에 추가된 스토리지 VM 자격 증명은 와 동일한 권한을 가진 사용자 계정이어야 `vsadmin` `vsadmin`합니다. 호스트는 ONTAP 8.2.2 이상을 실행하는 스토리지 시스템에 있어야 합니다.

. 왼쪽 탐색 창에서 VM을 마우스 오른쪽 단추로 클릭하고 드롭다운 목록에서 * SnapCenter Plug-in for VMware vSphere * 를 선택한 다음 보조 드롭다운 목록에서 * Restore * 를 선택하여 마법사를 시작합니다.
. 복원 * 마법사의 * 백업 선택 * 페이지에서 복원할 백업 스냅샷을 선택합니다.
+
특정 백업 이름 또는 일부 백업 이름을 검색하거나 필터 아이콘을 선택하고 날짜 및 시간 범위를 선택하고, VMware 스냅샷이 포함된 백업을 포함할지 여부, 마운트된 백업을 사용할지 여부 및 위치를 선택하여 백업 목록을 필터링할 수 있습니다. 확인 * 을 선택하여 마법사로 돌아갑니다.

. 범위 선택 * 페이지의 * 범위 복원 * 필드에서 * 전체 가상 시스템 * 을 선택한 다음 복원 위치를 선택하고 백업을 마운트할 대상 정보를 입력합니다.
+
VM name* 필드에 동일한 VM 이름이 있으면 새 VM 이름 형식은 "<VM_name>_<timestamp>"입니다.

+
부분 백업을 복원할 때 복원 작업은 * 범위 선택 * 페이지를 건너뜁니다.

. Select Location * 페이지에서 복구된 데이터 저장소의 위치를 선택합니다.
+
SnapCenter Plug-in for VMware vSphere 4.5 이상에서는 FlexGroup 볼륨에 대한 보조 스토리지를 선택할 수 있습니다.

. 요약 페이지를 검토한 다음 * 마침 * 을 선택합니다.
. 선택 사항: 화면 하단의 * Recent Tasks * 를 선택하여 작업 진행 상황을 모니터링합니다.
+
업데이트된 정보를 표시하려면 화면을 새로 고칩니다.



.작업을 마친 후
* IP 주소를 변경합니다
+
다른 위치로 복원한 경우 정적 IP 주소를 구성할 때 IP 주소 충돌을 방지하기 위해 새로 생성된 VM의 IP 주소를 변경해야 합니다.

* 복원된 VM을 리소스 그룹에 추가합니다
+
VM이 복원되지만 이전 리소스 그룹에 자동으로 추가되지 않습니다. 따라서 복원된 VM을 해당 리소스 그룹에 수동으로 추가해야 합니다.


