---
sidebar: sidebar 
permalink: scpivs44_manage_policies.html 
keywords:  
summary: VMware vSphere용 SnapCenter 플러그인에 대한 백업 정책을 생성, 수정, 보기, 분리 및 삭제할 수 있습니다. 데이터 보호 작업을 수행하려면 정책이 필요합니다. 
---
= 정책 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware vSphere용 SnapCenter 플러그인에 대한 백업 정책을 생성, 수정, 보기, 분리 및 삭제할 수 있습니다. 데이터 보호 작업을 수행하려면 정책이 필요합니다.



== 정책을 분리합니다

이러한 정책이 리소스에 대한 데이터 보호를 더 이상 제어하지 않도록 하려는 경우 SnapCenter VMware 플러그인 리소스 그룹에서 정책을 분리할 수 있습니다. 정책을 제거하거나 스케줄 빈도를 수정하기 전에 먼저 정책을 분리해야 합니다.

SnapCenter VMware 플러그인 리소스 그룹에서 정책을 분리하는 지침은 SnapCenter 리소스 그룹에 대한 지침과 다릅니다. VMware vSphere 웹 클라이언트 리소스 그룹의 경우 모든 정책을 분리할 수 있으며, 정책 없이 리소스 그룹이 남게 됩니다. 그러나 해당 리소스 그룹에 대해 데이터 보호 작업을 수행하려면 적어도 하나의 정책을 연결해야 합니다.

.단계
. VMware vSphere 웹 클라이언트의 왼쪽 탐색 창에서 * Resource Groups * 를 클릭한 다음 리소스 그룹을 선택하고 * Edit * 를 클릭합니다.
. 리소스 그룹 편집 * 마법사의 * 정책 * 페이지에서 분리할 정책 옆에 있는 확인 표시를 지웁니다.
+
정책을 확인하여 리소스 그룹에 정책을 추가할 수도 있습니다.

. 마법사의 나머지 부분에서 리소스 그룹을 추가로 수정한 후 * Finish * 를 클릭합니다.




== 정책을 수정합니다

SnapCenter Plug-in for VMware vSphere 리소스 그룹에 대한 정책을 수정할 수 있습니다. 정책이 리소스 그룹에 연결되어 있는 동안 빈도, 복제 옵션, 스냅샷 복사본 보존 설정 또는 스크립트 정보를 수정할 수 있습니다.

SnapCenter VMware 플러그인 백업 정책을 수정하는 것은 SnapCenter 애플리케이션 기반 플러그인에 대한 백업 정책을 수정하는 것과는 다릅니다. 플러그인 정책을 수정할 때 리소스 그룹에서 정책을 분리할 필요가 없습니다.

복제 또는 보존 설정을 수정하기 전에 가능한 결과를 고려해야 합니다.

* 복제 또는 보존 설정을 높입니다
+
백업은 새 설정에 도달할 때까지 계속 누적됩니다.

* 복제 또는 보존 설정을 줄입니다
+
새 설정을 초과하는 백업은 다음 백업을 수행할 때 삭제됩니다.




NOTE: SnapCenter VMware 플러그인 정책 스케줄을 수정하려면 플러그인 리소스 그룹에서 스케줄을 수정해야 합니다.

.단계
. VMware vSphere 웹 클라이언트의 왼쪽 탐색 창에서 * Policies * 를 클릭한 다음 정책을 선택하고 * Edit * 를 클릭합니다.
. 정책 필드를 수정합니다.
. 완료되면 * 업데이트 * 를 클릭합니다.


변경 사항은 다음 예약 백업을 수행할 때 적용됩니다.



== 정책을 삭제합니다

VMware vSphere용 SnapCenter 플러그인에 대해 구성된 백업 정책이 더 이상 필요하지 않은 경우 이를 삭제할 수 있습니다.

SnapCenter를 삭제하려면 먼저 가상 어플라이언스의 모든 리소스 그룹에서 정책을 분리해야 합니다.

.단계
. VMware vSphere 웹 클라이언트의 왼쪽 탐색 창에서 * Policies * 를 클릭한 다음 정책을 선택하고 * Remove * 를 클릭합니다.
. 확인 대화 상자에서 * 확인 * 을 클릭합니다.

