---
sidebar: sidebar 
permalink: scv48_audit_logs.html 
keywords:  
summary: 감사 로그는 누가 언제 무엇을 했는지 추적할 수 있습니다. 감사 로그는 시간순으로 이벤트 모음이며 어플라이언스 내의 파일에 기록됩니다. 
---
= 감사 로그
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
감사 로그는 시간 순으로 이벤트 모음으로, 어플라이언스 내의 파일에 기록됩니다. 감사 로그 파일은 에서 생성됩니다 `/var/log/netapp/audit` 위치 및 파일 이름은 다음 명명 규칙 중 하나를 따릅니다.

* audit.log: 사용 중인 활성 감사 로그 파일입니다.
* 감사 - %d{yyyy-mm-dd-HH-MM-ss}.log.gz: 감사 로그 파일에 롤오버됨. 파일 이름의 날짜와 시간은 파일이 생성된 시점을 나타냅니다(예: audit-2022-12-15-16-28-01.log.gz).


SCV 플러그인 사용자 인터페이스에서 * 대시보드 * > * 설정 * > * 감사 로그 * 탭에서 감사 로그 세부 정보를 보고 내보낼 수 있습니다. 감사 로그에서 작업 감사를 볼 수 있습니다. 감사 로그는 지원 번들과 함께 다운로드됩니다.

이메일 설정이 구성된 경우 SCV는 감사 로그 무결성 검증에 실패할 경우 이메일 알림을 보냅니다. 감사 로그 무결성 확인 실패는 파일 중 하나가 변조되거나 삭제될 때 발생할 수 있습니다.

감사 파일의 기본 구성은 다음과 같습니다.

* 사용 중인 감사 로그 파일은 최대 10MB까지 증가할 수 있습니다
* 최대 10개의 감사 로그 파일이 보존됩니다


기본 구성을 수정하려면 /opt/netapp/scvservice/standalone_aegis/etc/scbr/scbr.properties 에 키 값 쌍을 추가하고 scvservice를 다시 시작하십시오.

감사 로그 파일의 구성은 다음과 같습니다.

* auditMaxROFiles = <xx>, 여기서 xx는 감사 로그 파일에 롤오버된 최대 개수입니다(예: auditMaxROFiles = 15).
* auditLogSize = <XX> MB, 여기서 xx는 파일 크기(MB)입니다(예: auditLogSize = 15MB).


롤오버된 감사 로그는 정기적으로 무결성을 확인합니다. SCV는 로그를 보고 무결성을 확인하는 REST API를 제공합니다. 기본 제공 일정이 트리거되고 다음 무결성 상태 중 하나가 할당됩니다.

|===


| 상태 | 설명 


| 변조되었습니다 | 감사 로그 파일 내용이 수정되었습니다 


| 정상 | 감사 로그 파일을 수정하지 않습니다 


| 롤오버 삭제 | * 감사 로그 파일은 보존 * 에 따라 삭제되며 기본적으로 10개의 파일만 보존됩니다 


| 예기치 않은 삭제 | 감사 로그 파일이 삭제됩니다 


| 활성 | * 감사 로그 파일이 사용 중입니다. * audit.log 에만 적용됩니다 
|===
이벤트는 다음 세 가지 주요 범주로 분류됩니다.

* 데이터 보호 이벤트
* 유지보수 콘솔 이벤트
* 관리 콘솔 이벤트




== 데이터 보호 이벤트

SCV의 리소스는 다음과 같습니다.

* 스토리지 시스템
* 리소스 그룹
* 정책
* 백업


다음 표에는 각 리소스에 대해 수행할 수 있는 작업이 나와 있습니다.

|===


| 리소스 | 운영 


| 스토리지 시스템 | 생성됨, 수정됨, 삭제됨 


| 리소스 그룹 | 생성됨, 수정됨, 삭제됨, 일시 중단됨, 다시 시작됨 


| 정책 | 생성됨, 수정됨, 삭제됨 


| 백업 | 생성됨, 이름 변경됨, 삭제됨, 마운트됨, 마운트 해제됨, VMDK 복구, VM 복구, VMDK 연결, VMDK 분리, 게스트 파일 복원 
|===


== 유지보수 콘솔 이벤트

유지보수 콘솔의 관리 작업을 감사합니다. 사용 가능한 유지보수 콘솔 옵션은 다음과 같습니다.

. 서비스 시작/중지
. 사용자 이름 및 암호를 변경합니다
. MySQL 패스워드 변경
. MySQL 백업을 구성합니다
. MySQL 백업을 복원합니다
. '성자' 사용자 암호를 변경합니다
. 시간대를 변경합니다
. NTP 서버를 변경합니다
. SSH 액세스를 해제합니다
. jail 디스크 크기를 늘립니다
. 업그레이드
. VMware Tools 설치(이 툴을 오픈 VM 툴로 교체)
. IP 주소 설정을 변경합니다
. 도메인 이름 검색 설정을 변경합니다
. 정적 경로를 변경합니다
. 진단 셸에 액세스합니다
. 원격 진단 액세스를 활성화합니다




== 관리 콘솔 이벤트

관리 콘솔 UI의 다음 작업이 감사됩니다.

* 설정
+
** 관리자 자격 증명을 변경합니다
** 시간대를 변경합니다
** NTP 서버를 변경합니다
** IPv4/IPv6 설정을 변경합니다


* 구성
+
** vCenter 자격 증명을 변경합니다
** 플러그인 활성화/비활성화



